# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@aashutoshrathi/word-wrap-1.2.6" = {
      name = "_at_aashutoshrathi_slash_word-wrap";
      packageName = "@aashutoshrathi/word-wrap";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@aashutoshrathi/word-wrap/-/word-wrap-1.2.6.tgz";
        sha512 = "1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==";
      };
    };
    "@es-joy/jsdoccomment-0.42.0" = {
      name = "_at_es-joy_slash_jsdoccomment";
      packageName = "@es-joy/jsdoccomment";
      version = "0.42.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@es-joy/jsdoccomment/-/jsdoccomment-0.42.0.tgz";
        sha512 = "R1w57YlVA6+YE01wch3GPYn6bCsrOV3YW/5oGGE2tmX6JcL9Nr+b5IikrjMPF+v9CV3ay+obImEdsDhovhJrzw==";
      };
    };
    "@eslint-community/eslint-utils-4.4.0" = {
      name = "_at_eslint-community_slash_eslint-utils";
      packageName = "@eslint-community/eslint-utils";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint-community/eslint-utils/-/eslint-utils-4.4.0.tgz";
        sha512 = "1/sA4dwrzBAyeUoQ6oxahHKmrZvsnLCg4RfxW3ZFGGmQkSNQPFNLV9CUEFQP1x9EYXHTo5p6xdhZM1Ne9p/AfA==";
      };
    };
    "@eslint-community/regexpp-4.10.0" = {
      name = "_at_eslint-community_slash_regexpp";
      packageName = "@eslint-community/regexpp";
      version = "4.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint-community/regexpp/-/regexpp-4.10.0.tgz";
        sha512 = "Cu96Sd2By9mCNTx2iyKOmq10v22jUVQv0lQnlGNy16oE9589yE+QADPbrMGCkA51cKZSg3Pu/aTJVTGfL/qjUA==";
      };
    };
    "@eslint/eslintrc-2.1.4" = {
      name = "_at_eslint_slash_eslintrc";
      packageName = "@eslint/eslintrc";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/eslintrc/-/eslintrc-2.1.4.tgz";
        sha512 = "269Z39MS6wVJtsoUl10L60WdkhJVdPG24Q4eZTH3nnF6lpvSShEK3wQjDX9JRWAUPvPh7COouPpU9IrqaZFvtQ==";
      };
    };
    "@eslint/js-8.57.0" = {
      name = "_at_eslint_slash_js";
      packageName = "@eslint/js";
      version = "8.57.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/js/-/js-8.57.0.tgz";
        sha512 = "Ys+3g2TaW7gADOJzPt83SJtCDhMjndcDMFVQ/Tj9iA1BfJzFKD9mAUXT3OenpuPHbI6P/myECxRJrofUsDx/5g==";
      };
    };
    "@girs/accountsservice-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_accountsservice-1.0";
      packageName = "@girs/accountsservice-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/accountsservice-1.0/-/accountsservice-1.0-1.0.0-3.2.7.tgz";
        sha512 = "KRdQ6sf/XvuAxu6+1fXR8gslOMsPrM/01Qtxz8eJt6B/XJr7iK8C22WBJMcG00LD5svoRsaObD13Bd3wvV4ddw==";
      };
    };
    "@girs/adw-1-1.4.2-3.2.7" = {
      name = "_at_girs_slash_adw-1";
      packageName = "@girs/adw-1";
      version = "1.4.2-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/adw-1/-/adw-1-1.4.2-3.2.7.tgz";
        sha512 = "ULD9Z8U6DFdrN5oD8kfu5Q2OEh6HzK2fQu0ujr8FHn7WSlq+/BMV48xUOE26JnFyIZQumiP/RKXl6flMWCIY4Q==";
      };
    };
    "@girs/atk-1.0-2.50.0-3.2.7" = {
      name = "_at_girs_slash_atk-1.0";
      packageName = "@girs/atk-1.0";
      version = "2.50.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/atk-1.0/-/atk-1.0-2.50.0-3.2.7.tgz";
        sha512 = "4HBiLdINigopQksxhZCToRHPh2oUjL32ogZ/JzHqrxB+SMF3wSNS2nuyRI/RRhx0wDIrq+8H9PgQ1gzsbhxdWg==";
      };
    };
    "@girs/cairo-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_cairo-1.0";
      packageName = "@girs/cairo-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/cairo-1.0/-/cairo-1.0-1.0.0-3.2.7.tgz";
        sha512 = "WeAyTY8tUoVe8W1IDbxOYDczWyUotg/7sjzWPv5TXQJJAe3vZ6TfkYPSIlnQHkQ43XfWhSa0JA2s5Oitttdu0g==";
      };
    };
    "@girs/cally-13-13.0.0-3.2.7" = {
      name = "_at_girs_slash_cally-13";
      packageName = "@girs/cally-13";
      version = "13.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/cally-13/-/cally-13-13.0.0-3.2.7.tgz";
        sha512 = "EAWBXhAyl1+W18mvPd0/awEWV7SqCyhrr6a5JLMxpfPv6JSokAiJcoEhRlR35bkh5HVxSHHWfchn7UKSKtnjeQ==";
      };
    };
    "@girs/clutter-13-13.0.0-3.2.7" = {
      name = "_at_girs_slash_clutter-13";
      packageName = "@girs/clutter-13";
      version = "13.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/clutter-13/-/clutter-13-13.0.0-3.2.7.tgz";
        sha512 = "2fu3+wfZu6E3jBpavdYtX0Zm1SeaI24gjAzPNRlw+MTY0KpJ0ZevSavQ2IbKlLai/wo1YMCUrHmkjhmS6kIDdw==";
      };
    };
    "@girs/cogl-13-13.0.0-3.2.7" = {
      name = "_at_girs_slash_cogl-13";
      packageName = "@girs/cogl-13";
      version = "13.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/cogl-13/-/cogl-13-13.0.0-3.2.7.tgz";
        sha512 = "oVIqRXYwf0tER8n/Sq0SyRzZm5svCN8/ZDZig33+j3YpW2T2S4zzC2Px2ZlYVExolawh9P6NXUWnRhnPIGyp+Q==";
      };
    };
    "@girs/cogl-2.0-2.0.0-3.2.7" = {
      name = "_at_girs_slash_cogl-2.0";
      packageName = "@girs/cogl-2.0";
      version = "2.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/cogl-2.0/-/cogl-2.0-2.0.0-3.2.7.tgz";
        sha512 = "YyAcGlkvsfUIpns/NfEw1VDWh7WUxysoeHO36Rn4LZCUK2gpq7VabwQIGNRemVyYG/l4x7SaEoIr9pFRuyHHRQ==";
      };
    };
    "@girs/coglpango-13-13.0.0-3.2.7" = {
      name = "_at_girs_slash_coglpango-13";
      packageName = "@girs/coglpango-13";
      version = "13.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/coglpango-13/-/coglpango-13-13.0.0-3.2.7.tgz";
        sha512 = "iiQFWtVYOyyiTiCjBT/g9K0H7cvxG56mEnz+wtrHVYDSrkI029xv+7b+FjOrrzlkoyRr8CfWnTAYHhpmhvatdg==";
      };
    };
    "@girs/freetype2-2.0-2.0.0-3.2.7" = {
      name = "_at_girs_slash_freetype2-2.0";
      packageName = "@girs/freetype2-2.0";
      version = "2.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/freetype2-2.0/-/freetype2-2.0-2.0.0-3.2.7.tgz";
        sha512 = "oapcm7uCVWyL9N7VHuBOxbCWTa9QoF1EX6DFAwpGK4gwVrkjedZ4kZuxtza1gsZrkmYlWNK66H7YShFHgUWdPw==";
      };
    };
    "@girs/gck-2-4.1.0-3.2.7" = {
      name = "_at_girs_slash_gck-2";
      packageName = "@girs/gck-2";
      version = "4.1.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gck-2/-/gck-2-4.1.0-3.2.7.tgz";
        sha512 = "6eOLKMxM3ZCWLDwXdT9a6THQZfCPvIXcsvtQDoYlef9Ud+8owU/JhyXuQWysGqbbCv01mbvLe58uQ+KChRNkcg==";
      };
    };
    "@girs/gcr-4-4.1.0-3.2.7" = {
      name = "_at_girs_slash_gcr-4";
      packageName = "@girs/gcr-4";
      version = "4.1.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gcr-4/-/gcr-4-4.1.0-3.2.7.tgz";
        sha512 = "B8zFgzzHgLfcH1JoZqWLEwKExR2hgSDV72sxvvJoiB+ka3VWOs76/+0KODvd+BRMuZvA7t+zkKdGJ1VKtFoRwA==";
      };
    };
    "@girs/gdesktopenums-3.0-3.0.0-3.2.7" = {
      name = "_at_girs_slash_gdesktopenums-3.0";
      packageName = "@girs/gdesktopenums-3.0";
      version = "3.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gdesktopenums-3.0/-/gdesktopenums-3.0-3.0.0-3.2.7.tgz";
        sha512 = "4MC7jc7CM9pyylzTcoxjWuDJt9Q4FQ2h5WospM2yyrE2GjdNESw5HRdT98Nt3vly2W5akPDudNGSqb3YCqhcPg==";
      };
    };
    "@girs/gdk-4.0-4.0.0-3.2.7" = {
      name = "_at_girs_slash_gdk-4.0";
      packageName = "@girs/gdk-4.0";
      version = "4.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gdk-4.0/-/gdk-4.0-4.0.0-3.2.7.tgz";
        sha512 = "NULHNgwiLjX3vEWDhxSwEmVrSDv2UZaozZcTg295sRdQ/SrpnT5fYT9iL/HnB7JE2H2SBdYnhUrK3SnvCOCb9g==";
      };
    };
    "@girs/gdkpixbuf-2.0-2.0.0-3.2.7" = {
      name = "_at_girs_slash_gdkpixbuf-2.0";
      packageName = "@girs/gdkpixbuf-2.0";
      version = "2.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gdkpixbuf-2.0/-/gdkpixbuf-2.0-2.0.0-3.2.7.tgz";
        sha512 = "/POHLvRlJ6QYO8Wkrj2PDQT2lYh1vJFOHcfWd/yhtr7P3WWKGqOEG5NJAg81bMG8UIZOrc00HALXfCgbAalKGg==";
      };
    };
    "@girs/gdm-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_gdm-1.0";
      packageName = "@girs/gdm-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gdm-1.0/-/gdm-1.0-1.0.0-3.2.7.tgz";
        sha512 = "U05ZfhCxfiUSj48z28g/wokHKB/+BoPfSSIUdmh3OjcX1ssw9hbr+W/C2aPK6TC/iQQT/XQbntbTwkIxqfLPsw==";
      };
    };
    "@girs/gio-2.0-2.78.0-3.2.7" = {
      name = "_at_girs_slash_gio-2.0";
      packageName = "@girs/gio-2.0";
      version = "2.78.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gio-2.0/-/gio-2.0-2.78.0-3.2.7.tgz";
        sha512 = "88GNniBwxAsXrfA+T1wNUxoQk8HivDZUVq1KF3ZsomrQyRDcwCgQLcLyC6c5ZAkg6xwnHZmTIWoYgITiee/lLA==";
      };
    };
    "@girs/gjs-3.2.9" = {
      name = "_at_girs_slash_gjs";
      packageName = "@girs/gjs";
      version = "3.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gjs/-/gjs-3.2.9.tgz";
        sha512 = "dJfCNdtt4OLRywlhKOc+h27l5KoOiDhbhkuuG/WaV/jn9KaQ1BMAyVWdBEZu6WzPJlsiWYujis0fe5ZJnrgoDA==";
      };
    };
    "@girs/gl-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_gl-1.0";
      packageName = "@girs/gl-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gl-1.0/-/gl-1.0-1.0.0-3.2.7.tgz";
        sha512 = "pYGo7+u0KCUG63am/zmwOAUosurCs/BxwVRsOAnOKnZppkjfTqssEdAz1YyetbPK/n8sbYjsSWae/yIJmYAgRw==";
      };
    };
    "@girs/glib-2.0-2.78.0-3.2.9" = {
      name = "_at_girs_slash_glib-2.0";
      packageName = "@girs/glib-2.0";
      version = "2.78.0-3.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/glib-2.0/-/glib-2.0-2.78.0-3.2.9.tgz";
        sha512 = "wcbnSojav6jc4//PYsAJPwXizFlz35/F+AHyFbvutOSdNz4xzzUUZqUhhH2lmoyR8WDvkVWBcQitCmYmPNe6Xg==";
      };
    };
    "@girs/gmodule-2.0-2.0.0-3.2.7" = {
      name = "_at_girs_slash_gmodule-2.0";
      packageName = "@girs/gmodule-2.0";
      version = "2.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gmodule-2.0/-/gmodule-2.0-2.0.0-3.2.7.tgz";
        sha512 = "7B+rAZ6grSYwSOz2p4h8hSKoK5QIuSVHEM7qGUTC6qpPiLvREcaBNGJSGgAMgxtRhyXPYVsUyLhMgUokrFUC+g==";
      };
    };
    "@girs/gnome-shell-45.0.0-beta9" = {
      name = "_at_girs_slash_gnome-shell";
      packageName = "@girs/gnome-shell";
      version = "45.0.0-beta9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gnome-shell/-/gnome-shell-45.0.0-beta9.tgz";
        sha512 = "MPl+4VFvoOiMma91PZkOujMkcosLBMZhxiLpSQXjUCG90iBtAKJAYUA8gI9cVLDjtv4aIPkKern5SIElsX5++g==";
      };
    };
    "@girs/gnomebg-4.0-4.0.0-3.2.7" = {
      name = "_at_girs_slash_gnomebg-4.0";
      packageName = "@girs/gnomebg-4.0";
      version = "4.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gnomebg-4.0/-/gnomebg-4.0-4.0.0-3.2.7.tgz";
        sha512 = "IEognkZ33/XpRmkrfXhV+eda4RnJa9rBcN8ACOHoLsSWQfy5VbRBtSPS12R9Qd5cFe2Qv34GKNk+y8AUU1+fGg==";
      };
    };
    "@girs/gnomebluetooth-3.0-3.0.0-3.2.7" = {
      name = "_at_girs_slash_gnomebluetooth-3.0";
      packageName = "@girs/gnomebluetooth-3.0";
      version = "3.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gnomebluetooth-3.0/-/gnomebluetooth-3.0-3.0.0-3.2.7.tgz";
        sha512 = "Spx/oflIgyioJWu5gZkxcHizFqA5LOI7hWUxPFSB1Pwz6H/+uIwDpMkS9CUbu2RVYV6sasrxcnxtd6XzXP2lWw==";
      };
    };
    "@girs/gnomedesktop-4.0-4.0.0-3.2.7" = {
      name = "_at_girs_slash_gnomedesktop-4.0";
      packageName = "@girs/gnomedesktop-4.0";
      version = "4.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gnomedesktop-4.0/-/gnomedesktop-4.0-4.0.0-3.2.7.tgz";
        sha512 = "NkfWGGFk3OUgAdaHByfXrtiM23YRUI6ab9JOAcMtgN2CdCNj3jxcQl47IjazvucjQZXA2ZJU+EOCcdxI5aS0Hw==";
      };
    };
    "@girs/gobject-2.0-2.78.0-3.2.9" = {
      name = "_at_girs_slash_gobject-2.0";
      packageName = "@girs/gobject-2.0";
      version = "2.78.0-3.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gobject-2.0/-/gobject-2.0-2.78.0-3.2.9.tgz";
        sha512 = "zszoqx7/z7KseQnc7WUXz1jgs3oYskT748cMKLQ7n4pRtL6klrTzlPbM42Szs+Uk6wOKJ+o+MMdcpb8znflDBg==";
      };
    };
    "@girs/graphene-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_graphene-1.0";
      packageName = "@girs/graphene-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/graphene-1.0/-/graphene-1.0-1.0.0-3.2.7.tgz";
        sha512 = "WVhfoZq2G7mpXSGjI65VzmCLYWIqlFJMHwsgG0nBYZig2zKdle4c4hm5SQu9HrTQWTTPpbt8BM3qPCH2rFISXg==";
      };
    };
    "@girs/gsk-4.0-4.0.0-3.2.7" = {
      name = "_at_girs_slash_gsk-4.0";
      packageName = "@girs/gsk-4.0";
      version = "4.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gsk-4.0/-/gsk-4.0-4.0.0-3.2.7.tgz";
        sha512 = "wwEUJVK7RuSqQdinAqry+jVj1JH5s+EAhJ2l+8St8UV6/ajCxz/yUtt/2ACM0bZ9GJhgzM2+C9C3iBw73ZdFHg==";
      };
    };
    "@girs/gtk-4.0-4.12.4-3.2.7" = {
      name = "_at_girs_slash_gtk-4.0";
      packageName = "@girs/gtk-4.0";
      version = "4.12.4-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gtk-4.0/-/gtk-4.0-4.12.4-3.2.7.tgz";
        sha512 = "av+FCDNb3AgQKJmlj9ZEj4/umOUafrn9WIOYDG9pGrSBdrkHxg7QucFg8ePteMgkLB32yceL3up8hFU0vVUkYQ==";
      };
    };
    "@girs/gvc-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_gvc-1.0";
      packageName = "@girs/gvc-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gvc-1.0/-/gvc-1.0-1.0.0-3.2.7.tgz";
        sha512 = "5B6YxXRzqo6JbZg4B8KtEOEsUhfEZYo9yESgf95lhWeUXpS6JjJFg/lQ85E/KFDQmKtAJ/UYglmLa8omVvH5DA==";
      };
    };
    "@girs/harfbuzz-0.0-8.2.1-3.2.7" = {
      name = "_at_girs_slash_harfbuzz-0.0";
      packageName = "@girs/harfbuzz-0.0";
      version = "8.2.1-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/harfbuzz-0.0/-/harfbuzz-0.0-8.2.1-3.2.7.tgz";
        sha512 = "2ISw/O1eW90P2jeeFuTZRBE6+z/VWCWCaYZOMTTDaF498PGljKtuexm0e5BEzVrbayU7EgSHhqxfnfpsgI2+eQ==";
      };
    };
    "@girs/json-1.0-1.7.1-3.2.7" = {
      name = "_at_girs_slash_json-1.0";
      packageName = "@girs/json-1.0";
      version = "1.7.1-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/json-1.0/-/json-1.0-1.7.1-3.2.7.tgz";
        sha512 = "MtYgGf3KJCdRoCs5NtxMYlznwvPLqAzjuYApbA02RR9bs/4sr6vfy4FdioZGdLC9krlFiiYoCZJaThglYbEiww==";
      };
    };
    "@girs/meta-13-13.0.0-3.2.7" = {
      name = "_at_girs_slash_meta-13";
      packageName = "@girs/meta-13";
      version = "13.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/meta-13/-/meta-13-13.0.0-3.2.7.tgz";
        sha512 = "sXvzaAC+9NND/3ma4fMGgrERscbT+j2sGQjsVsLpubzNzWDtOc4AkeV8OD8dopbksnnTS6NA7dbwdpwtDBZ7xA==";
      };
    };
    "@girs/mtk-13-13.0.0-3.2.7" = {
      name = "_at_girs_slash_mtk-13";
      packageName = "@girs/mtk-13";
      version = "13.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/mtk-13/-/mtk-13-13.0.0-3.2.7.tgz";
        sha512 = "x6s0192AB90AbG6n26nOMS5q1uxxmeWMyStVUUmcdsd7WLW0IVLAGOaPIyB/KS4W2iBIYLOTIzUBfCT5geAsIA==";
      };
    };
    "@girs/nm-1.0-1.45.1-3.2.7" = {
      name = "_at_girs_slash_nm-1.0";
      packageName = "@girs/nm-1.0";
      version = "1.45.1-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/nm-1.0/-/nm-1.0-1.45.1-3.2.7.tgz";
        sha512 = "UCES5B76liszdKvHgFPRSThGHENxBCXb/QurNkJyqPRB6QvIC7NpenRX0oig3S62LbPNFCUNskGMw8Yt3pZwtg==";
      };
    };
    "@girs/pango-1.0-1.51.0-3.2.7" = {
      name = "_at_girs_slash_pango-1.0";
      packageName = "@girs/pango-1.0";
      version = "1.51.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/pango-1.0/-/pango-1.0-1.51.0-3.2.7.tgz";
        sha512 = "wxVVMrZnaWkgBmvTM4rWE20whh0CTRiXINgmK9V2NOdJHUUD3HqIvRxChG6YJmXQcb9h4Gcgpr+OyP34IgP2Sg==";
      };
    };
    "@girs/pangocairo-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_pangocairo-1.0";
      packageName = "@girs/pangocairo-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/pangocairo-1.0/-/pangocairo-1.0-1.0.0-3.2.7.tgz";
        sha512 = "94OAV/UOOO9VZ7d2W9D2SB7FIDfuUHESRGWTq1kq0XGL8o9P8Y4sKB7v2y6CRZTs3IML+IBI1qG9BDIdcNXnUA==";
      };
    };
    "@girs/polkit-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_polkit-1.0";
      packageName = "@girs/polkit-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/polkit-1.0/-/polkit-1.0-1.0.0-3.2.7.tgz";
        sha512 = "C01SGikKSvk6AalMyBaDc33/gvxuiuA9oQYqaf6MEQpOfe466BE5IhZl8L/6VjwVMmAGepFVcjwS5fxaRyioZQ==";
      };
    };
    "@girs/polkitagent-1.0-1.0.0-3.2.7" = {
      name = "_at_girs_slash_polkitagent-1.0";
      packageName = "@girs/polkitagent-1.0";
      version = "1.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/polkitagent-1.0/-/polkitagent-1.0-1.0.0-3.2.7.tgz";
        sha512 = "YlWtpFISpJR6qZhbL4W59vIFghiQ79EAev+QeqB4K3H9bw1tsoipbFVAqKqxyZFJTDSxSlGOpuVtcJ4EuO77HQ==";
      };
    };
    "@girs/shell-13-13.0.0-3.2.7" = {
      name = "_at_girs_slash_shell-13";
      packageName = "@girs/shell-13";
      version = "13.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/shell-13/-/shell-13-13.0.0-3.2.7.tgz";
        sha512 = "RrjHDZT8lj3uQ6QUg+Pb3AQOPhfJlPbFADZ/wudL1HdLa3GPNrmR1J7pxzXj5VtGWb9DJFjUnqBIyGU2iLkzlA==";
      };
    };
    "@girs/shew-0-0.0.0-3.2.7" = {
      name = "_at_girs_slash_shew-0";
      packageName = "@girs/shew-0";
      version = "0.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/shew-0/-/shew-0-0.0.0-3.2.7.tgz";
        sha512 = "TwFEU3OEPm05MtLmKTTb2Ekb4xp36So+VMYuy59NASCKFbhr+I9wGDU95ZXeztF0+/8wHQpklX0MG3KrVWmzqw==";
      };
    };
    "@girs/st-13-13.0.0-3.2.7" = {
      name = "_at_girs_slash_st-13";
      packageName = "@girs/st-13";
      version = "13.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/st-13/-/st-13-13.0.0-3.2.7.tgz";
        sha512 = "v39kFYYY3arbNELzseoRuKkN9hJIJG7ZpFbTGwRuB2pB1sfku3WJpfHPALwPg0uCvpDfSTfxTZ2Fg6R3qFWEdA==";
      };
    };
    "@girs/upowerglib-1.0-0.99.1-3.2.7" = {
      name = "_at_girs_slash_upowerglib-1.0";
      packageName = "@girs/upowerglib-1.0";
      version = "0.99.1-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/upowerglib-1.0/-/upowerglib-1.0-0.99.1-3.2.7.tgz";
        sha512 = "Ss0U2Q6lQ+aLVnddfulAvBJJjwpckV92Z3ivSDZ4VeCqi0dsiInVHlmHUC58Yb/A7EuCplL97hHax4orAgvAFQ==";
      };
    };
    "@girs/xfixes-4.0-4.0.0-3.2.7" = {
      name = "_at_girs_slash_xfixes-4.0";
      packageName = "@girs/xfixes-4.0";
      version = "4.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/xfixes-4.0/-/xfixes-4.0-4.0.0-3.2.7.tgz";
        sha512 = "MpV1+qiNX/8HadIK0Rnh+18S9OBqe2lcILdjVepQGn3lZx0QITPvY1XSdu835jYnTp+/izJWZGqZ9M/ZKI7hCg==";
      };
    };
    "@girs/xlib-2.0-2.0.0-3.2.7" = {
      name = "_at_girs_slash_xlib-2.0";
      packageName = "@girs/xlib-2.0";
      version = "2.0.0-3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/xlib-2.0/-/xlib-2.0-2.0.0-3.2.7.tgz";
        sha512 = "c4+y9V1BN7u0o2ijVuvT9WzEt7IvSJW/Dt4N7qQdTWfLnsQABPMnLuKQsZ6GRqPWBt+JBH0sOSR0tHBMLATC0g==";
      };
    };
    "@humanwhocodes/config-array-0.11.14" = {
      name = "_at_humanwhocodes_slash_config-array";
      packageName = "@humanwhocodes/config-array";
      version = "0.11.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/config-array/-/config-array-0.11.14.tgz";
        sha512 = "3T8LkOmg45BV5FICb15QQMsyUSWrQ8AygVfC7ZG32zOalnqrilm018ZVCw0eapXux8FtA33q8PSRSstjee3jSg==";
      };
    };
    "@humanwhocodes/module-importer-1.0.1" = {
      name = "_at_humanwhocodes_slash_module-importer";
      packageName = "@humanwhocodes/module-importer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/module-importer/-/module-importer-1.0.1.tgz";
        sha512 = "bxveV4V8v5Yb4ncFTT3rPSgZBOpCkjfK0y4oVVVJwIuDVBRMDXrPyXRL988i5ap9m9bnyEEjWfm5WkBmtffLfA==";
      };
    };
    "@humanwhocodes/object-schema-2.0.2" = {
      name = "_at_humanwhocodes_slash_object-schema";
      packageName = "@humanwhocodes/object-schema";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/object-schema/-/object-schema-2.0.2.tgz";
        sha512 = "6EwiSjwWYP7pTckG6I5eyFANjPhmPjUX9JRLUSfNPC7FX7zK9gyZAfUEaECL6ALTpGX5AjnBq3C9XmVWPitNpw==";
      };
    };
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.8" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
        sha512 = "oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      };
    };
    "@ungap/structured-clone-1.2.0" = {
      name = "_at_ungap_slash_structured-clone";
      packageName = "@ungap/structured-clone";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ungap/structured-clone/-/structured-clone-1.2.0.tgz";
        sha512 = "zuVdFrMJiuCDQUMCzQaD6KL28MjnqqN8XnAqiEq9PNm/hCPTSGfrXCOfwj1ow4LFb/tNymJPwsNbVePc1xFqrQ==";
      };
    };
    "acorn-8.11.3" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.11.3.tgz";
        sha512 = "Y9rRfJG5jcKOE0CLisYbojUjIrIEE7AGMzA/Sm4BslANhbS+cDMpgBdcPT91oJ7OuJ9hYJBx59RjbhxVnrF8Xg==";
      };
    };
    "acorn-jsx-5.3.2" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-5.3.2.tgz";
        sha512 = "rq9s+JNhf0IChjtDXxllJ7g41oZk5SlXtp0LHwyA5cejwn7vKmKp4pPri6YEePv2PU65sAsegbXtIinmDFDXgQ==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "are-docs-informative-0.0.2" = {
      name = "are-docs-informative";
      packageName = "are-docs-informative";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-docs-informative/-/are-docs-informative-0.0.2.tgz";
        sha512 = "ixiS0nLNNG5jNQzgZJNoUpBKdo9yTYZMGJ+QgT2jmjR7G7+QHRCc4v6LQ3NgE7EBJq+o0ams3waJwkrlBom8Ig==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "builtin-modules-3.3.0" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-3.3.0.tgz";
        sha512 = "zhaCDicdLuWN5UbN5IMnFqNMhNfo919sH85y2/ea+5Yg9TsTkeZxpL+JLbp6cgYFS4sRLp3YV4S6yDuqVWHYOw==";
      };
    };
    "callsites-3.1.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
        sha512 = "P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "comment-parser-1.4.1" = {
      name = "comment-parser";
      packageName = "comment-parser";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/comment-parser/-/comment-parser-1.4.1.tgz";
        sha512 = "buhp5kePrmda3vhc5B9t7pUQXAb2Tnd0qgpkIhPhkHXxJpiPJ11H0ZEU0oBpJ2QztSbzG/ZxMj/CHsYJqRHmyg==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "deep-is-0.1.4" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.4.tgz";
        sha512 = "oIPzksmTg4/MriiaYGO+okXDT7ztn/w3Eptv/+gSIdMdKsJo0u4CfYNFJPy+4SKMuCqGw2wxnA+URMg3t8a/bQ==";
      };
    };
    "doctrine-3.0.0" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-3.0.0.tgz";
        sha512 = "yS+Q5i3hBf7GBkd4KG8a7eBNNWNGLTaEwwYWUijIYM7zrlYDM0BFXHjjPWlWZ1Rg7UaddZeIDmi9jF3HmqiQ2w==";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "eslint-8.57.0" = {
      name = "eslint";
      packageName = "eslint";
      version = "8.57.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint/-/eslint-8.57.0.tgz";
        sha512 = "dZ6+mexnaTIbSBZWgou51U6OmzIhYM2VcNdtiTtI7qPNZm35Akpr0f6vtw3w1Kmn5PYo+tZVfh13WrhpS6oLqQ==";
      };
    };
    "eslint-plugin-jsdoc-48.2.1" = {
      name = "eslint-plugin-jsdoc";
      packageName = "eslint-plugin-jsdoc";
      version = "48.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-plugin-jsdoc/-/eslint-plugin-jsdoc-48.2.1.tgz";
        sha512 = "iUvbcyDZSO/9xSuRv2HQBw++8VkV/pt3UWtX9cpPH0l7GKPq78QC/6+PmyQHHvNZaTjAce6QVciEbnc6J/zH5g==";
      };
    };
    "eslint-scope-7.2.2" = {
      name = "eslint-scope";
      packageName = "eslint-scope";
      version = "7.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-scope/-/eslint-scope-7.2.2.tgz";
        sha512 = "dOt21O7lTMhDM+X9mB4GX+DZrZtCUJPL/wlcTqxyrx5IvO0IYtILdtrQGQp+8n5S0gwSVmOf9NQrjMOgfQZlIg==";
      };
    };
    "eslint-visitor-keys-3.4.3" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "3.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-3.4.3.tgz";
        sha512 = "wpc+LXeiyiisxPlEkUzU6svyS1frIO3Mgxj1fdy7Pm8Ygzguax2N3Fa/D/ag1WqbOprdI+uY6wMUl8/a2G+iag==";
      };
    };
    "espree-9.6.1" = {
      name = "espree";
      packageName = "espree";
      version = "9.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-9.6.1.tgz";
        sha512 = "oruZaFkjorTpF32kDSI5/75ViwGeZginGGy2NoOSg3Q9bnwlnmDm4HLnkl0RE3n+njDXR037aY1+x58Z/zFdwQ==";
      };
    };
    "esquery-1.5.0" = {
      name = "esquery";
      packageName = "esquery";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esquery/-/esquery-1.5.0.tgz";
        sha512 = "YQLXUplAwJgCydQ78IMJywZCceoqk1oH01OERdSAJc/7U2AylwjhSCLDEtqwg811idIS/9fIU5GjG73IgjKMVg==";
      };
    };
    "esrecurse-4.3.0" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.3.0.tgz";
        sha512 = "KmfKL3b6G+RXvP8N1vr3Tq1kL/oCFgn2NYXEtqP8/L3pKapUA4G8cFVaoF3SU323CD4XypR/ffioHmkti6/Tag==";
      };
    };
    "estraverse-5.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.3.0.tgz";
        sha512 = "MMdARuVEQziNTeJD8DgMqmhwR11BRQ/cBP+pLtYdSTnf3MIO8fFeiINEbX36ZdNlfU/7A9f3gUw49B3oQsvwBA==";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha512 = "DCXu6Ifhqcks7TZKY3Hxp3y6qphY5SJZmrWMDrKcERSOXWQdMhU9Ig/PYrzyw/ul9jOIyh0N4M0tbC5hodg8dw==";
      };
    };
    "fastq-1.17.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.17.0.tgz";
        sha512 = "zGygtijUMT7jnk3h26kUms3BkSDp4IfIKjmnqI2tvx6nuBfiF1UqOxbnLfzdv+apBy+53oaImsKtMw/xYbW+1w==";
      };
    };
    "file-entry-cache-6.0.1" = {
      name = "file-entry-cache";
      packageName = "file-entry-cache";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-entry-cache/-/file-entry-cache-6.0.1.tgz";
        sha512 = "7Gps/XWymbLk2QLYK4NzpMOrYjMhdIxXuIvy2QBsLE6ljuodKvdkWs/cpyJJ3CVIVpH0Oi1Hvg1ovbMzLdFBBg==";
      };
    };
    "find-up-5.0.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-5.0.0.tgz";
        sha512 = "78/PXT1wlLLDgTzDs7sjq9hzz0vXD+zn+7wypEe4fXQxCmdmqfGsEPQxmiCSQI3ajFV91bVSsvNtrJRiW6nGng==";
      };
    };
    "flat-cache-3.2.0" = {
      name = "flat-cache";
      packageName = "flat-cache";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/flat-cache/-/flat-cache-3.2.0.tgz";
        sha512 = "CYcENa+FtcUKLmhhqyctpclsq7QF38pKjZHsGNiSQF5r4FtoKDWabFDl3hzaEQMvT1LHEysw5twgLvpYYb4vbw==";
      };
    };
    "flatted-3.2.9" = {
      name = "flatted";
      packageName = "flatted";
      version = "3.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/flatted/-/flatted-3.2.9.tgz";
        sha512 = "36yxDn5H7OFZQla0/jFJmbIKTdZAQHngCedGxiMmpNfEZM0sdEeT+WczLQrjK6D7o2aiyLYDnkw0R3JK0Qv1RQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "glob-parent-6.0.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-6.0.2.tgz";
        sha512 = "XxwI8EOhVQgWp6iDL+3b0r86f4d6AX6zSU55HfB4ydCEuXLXc5FcYeOu+nnGftS4TEju/11rt4KJPTMgbfmv4A==";
      };
    };
    "globals-13.24.0" = {
      name = "globals";
      packageName = "globals";
      version = "13.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-13.24.0.tgz";
        sha512 = "AhO5QUcj8llrbG09iWhPU2B204J1xnPeL8kQmVorSsy+Sjj1sk8gIyh6cUocGmH4L0UuhAJy+hJMRA4mgA4mFQ==";
      };
    };
    "graphemer-1.4.0" = {
      name = "graphemer";
      packageName = "graphemer";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphemer/-/graphemer-1.4.0.tgz";
        sha512 = "EtKwoO6kxCL9WO5xipiHTZlSzBm7WLT627TqC/uVRd0HKmq8NXyebnNYxDoBi7wt8eTWrUrKXCOVaFq9x1kgag==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "ignore-5.3.0" = {
      name = "ignore";
      packageName = "ignore";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-5.3.0.tgz";
        sha512 = "g7dmpshy+gD7mh88OC9NwSGTKoc3kyLAZQRU1mt53Aw/vnvfXnbC+F/7F7QoYVKbV+KNvJx8wArewKy1vXMtlg==";
      };
    };
    "import-fresh-3.3.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.3.0.tgz";
        sha512 = "veYYhQa+D1QBKznvhUHxb8faxlrwUnxseDAbAp457E0wLNio2bOSKnjYDhMj+YiAq61xrMGhQk9iXVk5FzgQMw==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha512 = "JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-builtin-module-3.2.1" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-3.2.1.tgz";
        sha512 = "BSLE3HnV2syZ0FK0iMA/yUGplUeMmNz4AW5fnTunbCIqZi4vG3WjJT9FHMy5D69xmAYBHXQhJdALdpwVxV501A==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-path-inside-3.0.3" = {
      name = "is-path-inside";
      packageName = "is-path-inside";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-inside/-/is-path-inside-3.0.3.tgz";
        sha512 = "Fd4gABb+ycGAmKou8eMftCupSir5lRxqf4aD/vd0cD2qc4HL07OjCeuHMr8Ro4CoMaeCKDB0/ECBOVWjTwUvPQ==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "js-yaml-4.1.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.0.tgz";
        sha512 = "wpxZs9NoxZaJESJGIZTyDEaYpl0FKSA+FB9aJiyemKhMwkxQg63h4T1KJgUGHpTqPDNRcmmYLugrRjJlBtWvRA==";
      };
    };
    "jsdoc-type-pratt-parser-4.0.0" = {
      name = "jsdoc-type-pratt-parser";
      packageName = "jsdoc-type-pratt-parser";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsdoc-type-pratt-parser/-/jsdoc-type-pratt-parser-4.0.0.tgz";
        sha512 = "YtOli5Cmzy3q4dP26GraSOeAhqecewG04hoO8DY56CH4KJ9Fvv5qKWUCCo3HZob7esJQHCv6/+bnTy72xZZaVQ==";
      };
    };
    "json-buffer-3.0.1" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.1.tgz";
        sha512 = "4bV5BfR2mqfQTJm+V5tPPdf+ZpuhiIvTuAB5g8kcrXOZpTT/QwwVRWBywX1ozr6lEuPdbHxwaJlm9G6mI2sfSQ==";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-stable-stringify-without-jsonify-1.0.1" = {
      name = "json-stable-stringify-without-jsonify";
      packageName = "json-stable-stringify-without-jsonify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz";
        sha512 = "Bdboy+l7tA3OGW6FjyFHWkP5LuByj1Tk33Ljyq0axyzdk9//JSi2u3fP1QSmd1KNwq6VOKYGlAu87CisVir6Pw==";
      };
    };
    "keyv-4.5.4" = {
      name = "keyv";
      packageName = "keyv";
      version = "4.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-4.5.4.tgz";
        sha512 = "oxVHkHR/EJf2CNXnWxRLW6mg7JyCCUcG0DtEGmL2ctUo1PNTin1PUil+r/+4r5MpVgC/fn1kjsx7mjSujKqIpw==";
      };
    };
    "levn-0.4.1" = {
      name = "levn";
      packageName = "levn";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.4.1.tgz";
        sha512 = "+bT2uH4E5LGE7h/n3evcS/sQlJXCpIp6ym8OWJ5eV6+67Dsql/LaaT7qJBAt2rzfoa/5QBGBhxDix1dMt2kQKQ==";
      };
    };
    "locate-path-6.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-6.0.0.tgz";
        sha512 = "iPZK6eYjbxRu3uB4/WZ3EsEIMJFMqAoopl3R+zuq0UjcAm/MO6KCweDgPfP3elTztoKP3KtnVHxTn2NHBSDVUw==";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "natural-compare-1.4.0" = {
      name = "natural-compare";
      packageName = "natural-compare";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/natural-compare/-/natural-compare-1.4.0.tgz";
        sha512 = "OWND8ei3VtNC9h7V60qff3SVobHr996CTwgxubgyQYEpg290h9J0buyECNNJexkFm5sOajh5G116RYA1c8ZMSw==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "optionator-0.9.3" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.9.3.tgz";
        sha512 = "JjCoypp+jKn1ttEFExxhetCKeJt9zhAgAve5FXHixTvFDW/5aEktX9bufBKLRRMdU7bNtpLfcGu94B3cdEJgjg==";
      };
    };
    "p-limit-3.1.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-3.1.0.tgz";
        sha512 = "TYOanM3wGwNGsZN2cVTYPArw454xnXj5qmWF1bEoAc4+cU/ol7GVh7odevjp1FNHduHc3KZMcFduxU5Xc6uJRQ==";
      };
    };
    "p-locate-5.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-5.0.0.tgz";
        sha512 = "LaNjtRWUBY++zB5nE/NwcaoMylSPk+S+ZHNB1TzdbMJMny6dynpAGt7X/tl/QYq3TIeE6nxHppbo2LGymrG5Pw==";
      };
    };
    "parent-module-1.0.1" = {
      name = "parent-module";
      packageName = "parent-module";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
        sha512 = "GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
      };
    };
    "path-exists-4.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
        sha512 = "ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "prelude-ls-1.2.1" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.2.1.tgz";
        sha512 = "vkcDPrRZo1QZLbn5RLGPpg/WmIQ65qoWWhcGKf/b5eplkkarX0m9z8ppCat4mlOqUsWpyNuYgO3VRyrYHSzX5g==";
      };
    };
    "punycode-2.3.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.3.1.tgz";
        sha512 = "vYt7UD1U9Wg6138shLtLOvdAu+8DsC/ilFtEVHcH+wydcSpNE20AfSOduf6MkRFahL5FY7X1oU7nKVZFtfq8Fg==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "resolve-from-4.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
        sha512 = "pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "semver-7.6.0" = {
      name = "semver";
      packageName = "semver";
      version = "7.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.6.0.tgz";
        sha512 = "EnwXhrlwXMk9gKu5/flx5sv/an57AkRplG3hTK68W7FRDN+k+OWBj65M7719OkA82XLBxrcX0KSHj+X5COhOVg==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "spdx-exceptions-2.4.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.4.0.tgz";
        sha512 = "hcjppoJ68fhxA/cjbN4T8N6uCUejN8yFw69ttpqtBeCbF3u13n7mb31NB9jKwGTTWWnt9IbRA/mf1FprYS8wfw==";
      };
    };
    "spdx-expression-parse-4.0.0" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-4.0.0.tgz";
        sha512 = "Clya5JIij/7C6bRR22+tnGXbc4VKlibKSVj2iHvVeX5iMW7s1SIQlqu699JkODJJIhh/pUu8L0/VLh8xflD+LQ==";
      };
    };
    "spdx-license-ids-3.0.16" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.16.tgz";
        sha512 = "eWN+LnM3GR6gPu35WxNgbGl8rmY1AEmoMDvL/QD6zYmPWgywxWqJWNdLGT+ke8dKNWrcYgYjPpG5gbTfghP8rw==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha512 = "N+8UisAXDGk8PFXP4HAzVR9nbfmVJ3zYLAWiTIoqC5v5isinhr+r5uaO8+7r3BMfuNIufIsA7RdpVgacC2cSpw==";
      };
    };
    "type-check-0.4.0" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.4.0.tgz";
        sha512 = "XleUoc9uwGXqjWwXaUTZAmzMcFZ5858QA2vvx1Ur5xIcixXIP+8LnFDgRplU30us6teqdlskFfu+ae4K79Ooew==";
      };
    };
    "type-fest-0.20.2" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.20.2.tgz";
        sha512 = "Ne+eE4r0/iWnpAxD852z3A+N0Bt5RN//NjJwRd2VFHEmrywxf5vsZlh4R6lixl6B+wz/8d+maTSAkN1FIkI3LQ==";
      };
    };
    "typescript-5.4.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.4.2.tgz";
        sha512 = "+2/g0Fds1ERlP6JsakQQDXjZdZMM+rqpamFZJEKh4kwTIn3iDkgKtby0CeNd5ATNZ4Ry1ax15TMx0W2V+miizQ==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yocto-queue-0.1.0" = {
      name = "yocto-queue";
      packageName = "yocto-queue";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz";
        sha512 = "rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==";
      };
    };
  };
  args = {
    name = "gnome-rectangle";
    packageName = "gnome-rectangle";
    version = "1.0.0";
    src = ./..;
    dependencies = [
      sources."@aashutoshrathi/word-wrap-1.2.6"
      sources."@es-joy/jsdoccomment-0.42.0"
      sources."@eslint-community/eslint-utils-4.4.0"
      sources."@eslint-community/regexpp-4.10.0"
      sources."@eslint/eslintrc-2.1.4"
      sources."@eslint/js-8.57.0"
      sources."@girs/accountsservice-1.0-1.0.0-3.2.7"
      sources."@girs/adw-1-1.4.2-3.2.7"
      sources."@girs/atk-1.0-2.50.0-3.2.7"
      sources."@girs/cairo-1.0-1.0.0-3.2.7"
      sources."@girs/cally-13-13.0.0-3.2.7"
      sources."@girs/clutter-13-13.0.0-3.2.7"
      sources."@girs/cogl-13-13.0.0-3.2.7"
      sources."@girs/cogl-2.0-2.0.0-3.2.7"
      sources."@girs/coglpango-13-13.0.0-3.2.7"
      sources."@girs/freetype2-2.0-2.0.0-3.2.7"
      sources."@girs/gck-2-4.1.0-3.2.7"
      sources."@girs/gcr-4-4.1.0-3.2.7"
      sources."@girs/gdesktopenums-3.0-3.0.0-3.2.7"
      sources."@girs/gdk-4.0-4.0.0-3.2.7"
      sources."@girs/gdkpixbuf-2.0-2.0.0-3.2.7"
      sources."@girs/gdm-1.0-1.0.0-3.2.7"
      sources."@girs/gio-2.0-2.78.0-3.2.7"
      sources."@girs/gjs-3.2.9"
      sources."@girs/gl-1.0-1.0.0-3.2.7"
      sources."@girs/glib-2.0-2.78.0-3.2.9"
      sources."@girs/gmodule-2.0-2.0.0-3.2.7"
      sources."@girs/gnome-shell-45.0.0-beta9"
      sources."@girs/gnomebg-4.0-4.0.0-3.2.7"
      sources."@girs/gnomebluetooth-3.0-3.0.0-3.2.7"
      sources."@girs/gnomedesktop-4.0-4.0.0-3.2.7"
      sources."@girs/gobject-2.0-2.78.0-3.2.9"
      sources."@girs/graphene-1.0-1.0.0-3.2.7"
      sources."@girs/gsk-4.0-4.0.0-3.2.7"
      sources."@girs/gtk-4.0-4.12.4-3.2.7"
      sources."@girs/gvc-1.0-1.0.0-3.2.7"
      sources."@girs/harfbuzz-0.0-8.2.1-3.2.7"
      sources."@girs/json-1.0-1.7.1-3.2.7"
      sources."@girs/meta-13-13.0.0-3.2.7"
      sources."@girs/mtk-13-13.0.0-3.2.7"
      sources."@girs/nm-1.0-1.45.1-3.2.7"
      sources."@girs/pango-1.0-1.51.0-3.2.7"
      sources."@girs/pangocairo-1.0-1.0.0-3.2.7"
      sources."@girs/polkit-1.0-1.0.0-3.2.7"
      sources."@girs/polkitagent-1.0-1.0.0-3.2.7"
      sources."@girs/shell-13-13.0.0-3.2.7"
      sources."@girs/shew-0-0.0.0-3.2.7"
      sources."@girs/st-13-13.0.0-3.2.7"
      sources."@girs/upowerglib-1.0-0.99.1-3.2.7"
      sources."@girs/xfixes-4.0-4.0.0-3.2.7"
      sources."@girs/xlib-2.0-2.0.0-3.2.7"
      sources."@humanwhocodes/config-array-0.11.14"
      sources."@humanwhocodes/module-importer-1.0.1"
      sources."@humanwhocodes/object-schema-2.0.2"
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.8"
      sources."@ungap/structured-clone-1.2.0"
      sources."acorn-8.11.3"
      sources."acorn-jsx-5.3.2"
      sources."ajv-6.12.6"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."are-docs-informative-0.0.2"
      sources."argparse-2.0.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."builtin-modules-3.3.0"
      sources."callsites-3.1.0"
      sources."chalk-4.1.2"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."comment-parser-1.4.1"
      sources."concat-map-0.0.1"
      sources."cross-spawn-7.0.3"
      sources."debug-4.3.4"
      sources."deep-is-0.1.4"
      sources."doctrine-3.0.0"
      sources."escape-string-regexp-4.0.0"
      sources."eslint-8.57.0"
      sources."eslint-plugin-jsdoc-48.2.1"
      sources."eslint-scope-7.2.2"
      sources."eslint-visitor-keys-3.4.3"
      sources."espree-9.6.1"
      sources."esquery-1.5.0"
      sources."esrecurse-4.3.0"
      sources."estraverse-5.3.0"
      sources."esutils-2.0.3"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fast-levenshtein-2.0.6"
      sources."fastq-1.17.0"
      sources."file-entry-cache-6.0.1"
      sources."find-up-5.0.0"
      sources."flat-cache-3.2.0"
      sources."flatted-3.2.9"
      sources."fs.realpath-1.0.0"
      sources."glob-7.2.3"
      sources."glob-parent-6.0.2"
      sources."globals-13.24.0"
      sources."graphemer-1.4.0"
      sources."has-flag-4.0.0"
      sources."ignore-5.3.0"
      sources."import-fresh-3.3.0"
      sources."imurmurhash-0.1.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-builtin-module-3.2.1"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-path-inside-3.0.3"
      sources."isexe-2.0.0"
      sources."js-yaml-4.1.0"
      sources."jsdoc-type-pratt-parser-4.0.0"
      sources."json-buffer-3.0.1"
      sources."json-schema-traverse-0.4.1"
      sources."json-stable-stringify-without-jsonify-1.0.1"
      sources."keyv-4.5.4"
      sources."levn-0.4.1"
      sources."locate-path-6.0.0"
      sources."lodash.merge-4.6.2"
      sources."lru-cache-6.0.0"
      sources."minimatch-3.1.2"
      sources."ms-2.1.2"
      sources."natural-compare-1.4.0"
      sources."once-1.4.0"
      sources."optionator-0.9.3"
      sources."p-limit-3.1.0"
      sources."p-locate-5.0.0"
      sources."parent-module-1.0.1"
      sources."path-exists-4.0.0"
      sources."path-is-absolute-1.0.1"
      sources."path-key-3.1.1"
      sources."prelude-ls-1.2.1"
      sources."punycode-2.3.1"
      sources."queue-microtask-1.2.3"
      sources."resolve-from-4.0.0"
      sources."reusify-1.0.4"
      sources."rimraf-3.0.2"
      sources."run-parallel-1.2.0"
      sources."semver-7.6.0"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."spdx-exceptions-2.4.0"
      sources."spdx-expression-parse-4.0.0"
      sources."spdx-license-ids-3.0.16"
      sources."strip-ansi-6.0.1"
      sources."strip-json-comments-3.1.1"
      sources."supports-color-7.2.0"
      sources."text-table-0.2.0"
      sources."type-check-0.4.0"
      sources."type-fest-0.20.2"
      sources."typescript-5.4.2"
      sources."uri-js-4.4.1"
      sources."which-2.0.2"
      sources."wrappy-1.0.2"
      sources."yallist-4.0.0"
      sources."yocto-queue-0.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Magnet/Rectangle like manual tiling";
      homepage = "https://github.com/acristoffers/gnome-rectangle#readme";
      license = "LGPL-3.0-or-later";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
