# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@es-joy/jsdoccomment-0.49.0" = {
      name = "_at_es-joy_slash_jsdoccomment";
      packageName = "@es-joy/jsdoccomment";
      version = "0.49.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@es-joy/jsdoccomment/-/jsdoccomment-0.49.0.tgz";
        sha512 = "xjZTSFgECpb9Ohuk5yMX5RhUEbfeQcuOp8IF60e+wyzWEF0M5xeSgqsfLtvPEX8BIyOX9saZqzuGPmZ8oWc+5Q==";
      };
    };
    "@eslint-community/eslint-utils-4.4.0" = {
      name = "_at_eslint-community_slash_eslint-utils";
      packageName = "@eslint-community/eslint-utils";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint-community/eslint-utils/-/eslint-utils-4.4.0.tgz";
        sha512 = "1/sA4dwrzBAyeUoQ6oxahHKmrZvsnLCg4RfxW3ZFGGmQkSNQPFNLV9CUEFQP1x9EYXHTo5p6xdhZM1Ne9p/AfA==";
      };
    };
    "@eslint-community/regexpp-4.12.1" = {
      name = "_at_eslint-community_slash_regexpp";
      packageName = "@eslint-community/regexpp";
      version = "4.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint-community/regexpp/-/regexpp-4.12.1.tgz";
        sha512 = "CCZCDJuduB9OUkFkY2IgppNZMi2lBQgD2qzwXkEia16cge2pijY/aXi96CJMquDMn3nJdlPV1A5KrJEXwfLNzQ==";
      };
    };
    "@eslint/config-array-0.19.0" = {
      name = "_at_eslint_slash_config-array";
      packageName = "@eslint/config-array";
      version = "0.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/config-array/-/config-array-0.19.0.tgz";
        sha512 = "zdHg2FPIFNKPdcHWtiNT+jEFCHYVplAXRDlQDyqy0zGx/q2parwh7brGJSiTxRk/TSMkbM//zt/f5CHgyTyaSQ==";
      };
    };
    "@eslint/core-0.9.0" = {
      name = "_at_eslint_slash_core";
      packageName = "@eslint/core";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/core/-/core-0.9.0.tgz";
        sha512 = "7ATR9F0e4W85D/0w7cU0SNj7qkAexMG+bAHEZOjo9akvGuhHE2m7umzWzfnpa0XAg5Kxc1BWmtPMV67jJ+9VUg==";
      };
    };
    "@eslint/eslintrc-3.2.0" = {
      name = "_at_eslint_slash_eslintrc";
      packageName = "@eslint/eslintrc";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/eslintrc/-/eslintrc-3.2.0.tgz";
        sha512 = "grOjVNN8P3hjJn/eIETF1wwd12DdnwFDoyceUJLYYdkpbwq3nLi+4fqrTAONx7XDALqlL220wC/RHSC/QTI/0w==";
      };
    };
    "@eslint/js-9.16.0" = {
      name = "_at_eslint_slash_js";
      packageName = "@eslint/js";
      version = "9.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/js/-/js-9.16.0.tgz";
        sha512 = "tw2HxzQkrbeuvyj1tG2Yqq+0H9wGoI2IMk4EOsQeX+vmd75FtJAzf+gTA69WF+baUKRYQ3x2kbLE08js5OsTVg==";
      };
    };
    "@eslint/object-schema-2.1.4" = {
      name = "_at_eslint_slash_object-schema";
      packageName = "@eslint/object-schema";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/object-schema/-/object-schema-2.1.4.tgz";
        sha512 = "BsWiH1yFGjXXS2yvrf5LyuoSIIbPrGUWob917o+BTKuZ7qJdxX8aJLRxs1fS9n6r7vESrq1OUqb68dANcFXuQQ==";
      };
    };
    "@eslint/plugin-kit-0.2.3" = {
      name = "_at_eslint_slash_plugin-kit";
      packageName = "@eslint/plugin-kit";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/plugin-kit/-/plugin-kit-0.2.3.tgz";
        sha512 = "2b/g5hRmpbb1o4GnTZax9N9m0FXzz9OV42ZzI4rDDMDuHUqigAiQCEWChBWCY4ztAGVRjoWT19v0yMmc5/L5kA==";
      };
    };
    "@girs/accountsservice-1.0-1.0.0-4.0.0-beta.17" = {
      name = "_at_girs_slash_accountsservice-1.0";
      packageName = "@girs/accountsservice-1.0";
      version = "1.0.0-4.0.0-beta.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/accountsservice-1.0/-/accountsservice-1.0-1.0.0-4.0.0-beta.17.tgz";
        sha512 = "cGD0GNwIhOEPqxePXEpOdggGEZTPXDCgQnTDnuS0usIQQeUvPkG3ccFAOTAkzzRIszmPPVj1qL8vm9LtUAYh2Q==";
      };
    };
    "@girs/adw-1-1.7.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_adw-1";
      packageName = "@girs/adw-1";
      version = "1.7.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/adw-1/-/adw-1-1.7.0-4.0.0-beta.19.tgz";
        sha512 = "T3KF0YcjMwomDtAYm9NobGe21tkd8u3ybf6ANLDX4sIyM07Xqtamix00Cj3ZCDZ0+tOPdRMkRRhXV1DGoo7OLw==";
      };
    };
    "@girs/atk-1.0-2.54.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_atk-1.0";
      packageName = "@girs/atk-1.0";
      version = "2.54.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/atk-1.0/-/atk-1.0-2.54.0-4.0.0-beta.19.tgz";
        sha512 = "gKzsnSBzrsxA0FIgYPCRVveNgc6udI9gbFM4Nkfl/w7TTh3R1Fc9w8q7t8Rog4Ek10EJzb+rw2zpc2e+WlXpJA==";
      };
    };
    "@girs/cairo-1.0-1.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_cairo-1.0";
      packageName = "@girs/cairo-1.0";
      version = "1.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/cairo-1.0/-/cairo-1.0-1.0.0-4.0.0-beta.19.tgz";
        sha512 = "nBI5oveqH0N7czBC95ofJ4Un5KKqK6guANE6O0OxkwuF6B3YxVqdNmF8O8i2tk3GIxBzwxkC0bi0Wb6X4tLR8g==";
      };
    };
    "@girs/cally-15-15.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_cally-15";
      packageName = "@girs/cally-15";
      version = "15.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/cally-15/-/cally-15-15.0.0-4.0.0-beta.19.tgz";
        sha512 = "bWHSUosGSwa0UKxBsO3MfnG9EFxtYfN5k/tTJtNFmWF0JOTiMwBgtvXSrxqPpnoRxHaGQ8f5QFQ20rH2kHtvkQ==";
      };
    };
    "@girs/clutter-15-15.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_clutter-15";
      packageName = "@girs/clutter-15";
      version = "15.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/clutter-15/-/clutter-15-15.0.0-4.0.0-beta.19.tgz";
        sha512 = "1LpSErfEKPh8tcysgL07++hWy2xsokJ+svbzub95ykXjFkibNrutJBWXmh6E3j5Hs61Va18JjyjPIfmGdVclPA==";
      };
    };
    "@girs/cogl-15-15.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_cogl-15";
      packageName = "@girs/cogl-15";
      version = "15.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/cogl-15/-/cogl-15-15.0.0-4.0.0-beta.19.tgz";
        sha512 = "GEsERs00Vi1TjvPDev05QonAQABSmLoLeNzDciIc9ZhPdDRAf8/MQAQYLqFx6+4U8OmvCNPYDC/t/n+6BwoqBA==";
      };
    };
    "@girs/cogl-2.0-2.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_cogl-2.0";
      packageName = "@girs/cogl-2.0";
      version = "2.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/cogl-2.0/-/cogl-2.0-2.0.0-4.0.0-beta.19.tgz";
        sha512 = "Fgb9k7Hi6PMZ944VUxYGDq0hG16BQz7NZ6knzXKzgvcP2LqIt4rlR2+TC5FkXRXlYV+SypsI8f4PuMvRp4N1+g==";
      };
    };
    "@girs/coglpango-15-15.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_coglpango-15";
      packageName = "@girs/coglpango-15";
      version = "15.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/coglpango-15/-/coglpango-15-15.0.0-4.0.0-beta.19.tgz";
        sha512 = "fNNwTYsGfMYcLNUkvWLr6OlAuMJMB+XWfppQhXL8NFX15d4AIaBFBHi8vdVRLf/buU2g8Yga52/zH/DJZN/8mg==";
      };
    };
    "@girs/freetype2-2.0-2.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_freetype2-2.0";
      packageName = "@girs/freetype2-2.0";
      version = "2.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/freetype2-2.0/-/freetype2-2.0-2.0.0-4.0.0-beta.19.tgz";
        sha512 = "xU3uVUXMY0MeLc2U4QgpWBQ6VSBtMKaqKRcRT7TrOM1etkLzGhh70SWt16xjqA6vrpF+wZ9TtndQZy2ky0gpwA==";
      };
    };
    "@girs/gck-2-4.3.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gck-2";
      packageName = "@girs/gck-2";
      version = "4.3.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gck-2/-/gck-2-4.3.0-4.0.0-beta.19.tgz";
        sha512 = "0oVamw4QWQSo2sDOmrfv8K5pV1h2yNDuD+64m0Y3Ciq+X/vSmmV6r1fsmF7hR64ISz8OtBALRydQ1dQ/m3z1bA==";
      };
    };
    "@girs/gcr-4-4.3.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gcr-4";
      packageName = "@girs/gcr-4";
      version = "4.3.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gcr-4/-/gcr-4-4.3.0-4.0.0-beta.19.tgz";
        sha512 = "WK8ytGrac+MvVOMaMVJb5+uWmVnxRbU6SwHxwosLmLAJOFJlzOL3LHtN1bkI92qtGfwG2+uAmS3ZOtEAbMJIvw==";
      };
    };
    "@girs/gdesktopenums-3.0-3.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gdesktopenums-3.0";
      packageName = "@girs/gdesktopenums-3.0";
      version = "3.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gdesktopenums-3.0/-/gdesktopenums-3.0-3.0.0-4.0.0-beta.19.tgz";
        sha512 = "YGRG54iOGknzbZjfY/OdiX0keoOvyjIjEPdWKNm7C4VrIrTmNxDlPorUoJf4aJcWuBfAXHQ8EupsrjMhGnULAQ==";
      };
    };
    "@girs/gdk-4.0-4.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gdk-4.0";
      packageName = "@girs/gdk-4.0";
      version = "4.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gdk-4.0/-/gdk-4.0-4.0.0-4.0.0-beta.19.tgz";
        sha512 = "mzUgED6t5lvCeX5r1QHozwYs1/gZmOuDegMHawvSOydSkScaP5tlwLrUgpB+iosOPibUeZScMSkXWsNd09Stng==";
      };
    };
    "@girs/gdkpixbuf-2.0-2.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gdkpixbuf-2.0";
      packageName = "@girs/gdkpixbuf-2.0";
      version = "2.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gdkpixbuf-2.0/-/gdkpixbuf-2.0-2.0.0-4.0.0-beta.19.tgz";
        sha512 = "h8+LofOkyChEhduPGWYI4XDi5bCb9h8aRhYU4p6CTWEAiWXE2a7EtPjdLKXkQADAL/xt3eQoF2t6ecFdYIoiEg==";
      };
    };
    "@girs/gdm-1.0-1.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gdm-1.0";
      packageName = "@girs/gdm-1.0";
      version = "1.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gdm-1.0/-/gdm-1.0-1.0.0-4.0.0-beta.19.tgz";
        sha512 = "mV4f+hzW+3Kd7JjvXWnB0NUH7AW3qAq1C26pUu3mkf6AbinHTuri+J15toW6K3htkl5Og193PMIpD4ETDguiOA==";
      };
    };
    "@girs/gio-2.0-2.82.2-4.0.0-beta.19" = {
      name = "_at_girs_slash_gio-2.0";
      packageName = "@girs/gio-2.0";
      version = "2.82.2-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gio-2.0/-/gio-2.0-2.82.2-4.0.0-beta.19.tgz";
        sha512 = "OM2E/mdNX3Z+X7mB8ZVFch4WbUqX1Y6hADiG9+LuGWsAOjPAVvDDUk5N4+34+BTPEfFHLGOdo8E7dI235jylCQ==";
      };
    };
    "@girs/gjs-4.0.0-beta.19" = {
      name = "_at_girs_slash_gjs";
      packageName = "@girs/gjs";
      version = "4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gjs/-/gjs-4.0.0-beta.19.tgz";
        sha512 = "tl+BjmMqqZH9xZcJZ2AwWI0sotGDc7qVPppAJNeFZFCgUDOFVWThZfkpZffZcQGNphn7wgU8HOvgZyrtVhrltw==";
      };
    };
    "@girs/gl-1.0-1.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gl-1.0";
      packageName = "@girs/gl-1.0";
      version = "1.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gl-1.0/-/gl-1.0-1.0.0-4.0.0-beta.19.tgz";
        sha512 = "uG/KCXgo2zHdtJGmiMJq5k8kv3B1QH3kl325dQkyE+G6/Ii7gsBepVsy1Gyew2bXPKU2UTUwIn8DDnLIhMHJZg==";
      };
    };
    "@girs/glib-2.0-2.82.2-4.0.0-beta.19" = {
      name = "_at_girs_slash_glib-2.0";
      packageName = "@girs/glib-2.0";
      version = "2.82.2-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/glib-2.0/-/glib-2.0-2.82.2-4.0.0-beta.19.tgz";
        sha512 = "mRUhcp7O65KQQkyrgiQpUzl1rY+TH4X+A98Kk67g3VjuA7Ei/lV4lcuZnW04HnXAGvQ3Qfkq877NmcDXRgb02g==";
      };
    };
    "@girs/gmodule-2.0-2.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gmodule-2.0";
      packageName = "@girs/gmodule-2.0";
      version = "2.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gmodule-2.0/-/gmodule-2.0-2.0.0-4.0.0-beta.19.tgz";
        sha512 = "whTYGLL63Hw1Tn9ZicpJRAMtkYiZwB3lrcln4ETFxyO1ckGTTZ5s17cWcrQjij27veVvjWcb5rmc93L5djeBpg==";
      };
    };
    "@girs/gnome-shell-47.0.0" = {
      name = "_at_girs_slash_gnome-shell";
      packageName = "@girs/gnome-shell";
      version = "47.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gnome-shell/-/gnome-shell-47.0.0.tgz";
        sha512 = "R2bjjFddsUsfDp9oLL/T0DSSYsg2hLuChK/6D+qdc76zvv+uGUG6VdbPFVQhb0HhpOKi3BvDoTRD6Rco66ZIBg==";
      };
    };
    "@girs/gnomebg-4.0-4.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gnomebg-4.0";
      packageName = "@girs/gnomebg-4.0";
      version = "4.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gnomebg-4.0/-/gnomebg-4.0-4.0.0-4.0.0-beta.19.tgz";
        sha512 = "eDeNaVOBAoYIjC5RiHfpDfS3PjAweSUsGc+jYWm/BdNkFtmUujlv/b+91nhCTN7iwWDuN5nRf2PEw0smFWvpoQ==";
      };
    };
    "@girs/gnomebluetooth-3.0-3.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gnomebluetooth-3.0";
      packageName = "@girs/gnomebluetooth-3.0";
      version = "3.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gnomebluetooth-3.0/-/gnomebluetooth-3.0-3.0.0-4.0.0-beta.19.tgz";
        sha512 = "seVQKnNVF06H3W2qB6utRYWTYsia5lqymyPVe41ALzWGfI0dgpnGIubKUslA7cx1U5a/wnGoaKvL6N1wysT0uw==";
      };
    };
    "@girs/gnomedesktop-4.0-4.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gnomedesktop-4.0";
      packageName = "@girs/gnomedesktop-4.0";
      version = "4.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gnomedesktop-4.0/-/gnomedesktop-4.0-4.0.0-4.0.0-beta.19.tgz";
        sha512 = "8v7BwRN6RRtx5KnamsnUUU63tem+WuOYQy2+AsiARWEqgZwb91yt25qpk2oii/0WeTleHVsh/00dmjksboloxw==";
      };
    };
    "@girs/gobject-2.0-2.82.2-4.0.0-beta.19" = {
      name = "_at_girs_slash_gobject-2.0";
      packageName = "@girs/gobject-2.0";
      version = "2.82.2-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gobject-2.0/-/gobject-2.0-2.82.2-4.0.0-beta.19.tgz";
        sha512 = "E1fCaIZvZ7K035Waa/vYOTqLKI47OSUX3wpMrD+DBlyfDLDCFvyXwaIrFsiKUVFJIxj1xxq7H2yCZvkYqkfklA==";
      };
    };
    "@girs/graphene-1.0-1.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_graphene-1.0";
      packageName = "@girs/graphene-1.0";
      version = "1.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/graphene-1.0/-/graphene-1.0-1.0.0-4.0.0-beta.19.tgz";
        sha512 = "TVich9PzcDhD0vECizmHydSTqUhzfIUw3iYi8Pu9bE4wT90gwkgzst9klrjd64oNCNBa3JYrI8xB1txD69kMIg==";
      };
    };
    "@girs/gsk-4.0-4.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gsk-4.0";
      packageName = "@girs/gsk-4.0";
      version = "4.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gsk-4.0/-/gsk-4.0-4.0.0-4.0.0-beta.19.tgz";
        sha512 = "UW2skBBR652PVCeTfnjcQ246099wmb9L2rq7C2MwPeV+n7hqnlIBEczdDKspZCvEIC0377Ds9kZeUYqprEBdfQ==";
      };
    };
    "@girs/gtk-4.0-4.16.3-4.0.0-beta.19" = {
      name = "_at_girs_slash_gtk-4.0";
      packageName = "@girs/gtk-4.0";
      version = "4.16.3-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gtk-4.0/-/gtk-4.0-4.16.3-4.0.0-beta.19.tgz";
        sha512 = "IPDbVzknnEs1G4XyYZxB+0cx6d1CBQjg/CJOgUCk4NTIrvxfzvcHBy4idyT/12ecOGsAx7AryqCkn4dhetYLqg==";
      };
    };
    "@girs/gvc-1.0-1.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_gvc-1.0";
      packageName = "@girs/gvc-1.0";
      version = "1.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/gvc-1.0/-/gvc-1.0-1.0.0-4.0.0-beta.19.tgz";
        sha512 = "b2KYzVB/I8YRUosUy0CDduFasS6AEP+lYDgo/O3xjwmkW35LclE7CoVuRxhYl2fpL8hvuM6VutpKBdzeMXdRCQ==";
      };
    };
    "@girs/harfbuzz-0.0-9.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_harfbuzz-0.0";
      packageName = "@girs/harfbuzz-0.0";
      version = "9.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/harfbuzz-0.0/-/harfbuzz-0.0-9.0.0-4.0.0-beta.19.tgz";
        sha512 = "m+rGrFJs6OUdz/WdG/lvXgJ6eSMW5vSPmtZDHoipDnY5LDMDfF0/tEc12RqPqJ7uF59czcYtpSa2gR4ZtrKHUA==";
      };
    };
    "@girs/meta-15-15.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_meta-15";
      packageName = "@girs/meta-15";
      version = "15.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/meta-15/-/meta-15-15.0.0-4.0.0-beta.19.tgz";
        sha512 = "XRVOb66tm/zteoZt1ST8X0jh6ZTB3JjFpxGYllQ+2tooOTW1CodbEkCjBq5JzhCD7hieOpgLF5KorPiDRNWKUw==";
      };
    };
    "@girs/mtk-15-15.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_mtk-15";
      packageName = "@girs/mtk-15";
      version = "15.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/mtk-15/-/mtk-15-15.0.0-4.0.0-beta.19.tgz";
        sha512 = "tdSeO4xGFrZAVkGxhOgt+Q3hicpzkPUajtpm6FI2SiO6UDtiC5i+2LwO1IuerlHTLKkuThZ+81s3JRiXYATKEg==";
      };
    };
    "@girs/nm-1.0-1.49.4-4.0.0-beta.19" = {
      name = "_at_girs_slash_nm-1.0";
      packageName = "@girs/nm-1.0";
      version = "1.49.4-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/nm-1.0/-/nm-1.0-1.49.4-4.0.0-beta.19.tgz";
        sha512 = "MMNqS9Yp+cfTdwE6NziFOjGA9iL0/3wArM6r8qF1Cr+cTbFIXXSWHcz98GFpH2xkRK0HQuyFIW0vbEoJdWbEPQ==";
      };
    };
    "@girs/pango-1.0-1.54.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_pango-1.0";
      packageName = "@girs/pango-1.0";
      version = "1.54.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/pango-1.0/-/pango-1.0-1.54.0-4.0.0-beta.19.tgz";
        sha512 = "O/tJNlRAdmuJFrw8pOMKZrYldgSLgAN9dOJrtQXSh4+6vFH7LQ9SnCKv+6hmJ6yJUnfzEtyOgWAhdmee/Hz3tQ==";
      };
    };
    "@girs/pangocairo-1.0-1.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_pangocairo-1.0";
      packageName = "@girs/pangocairo-1.0";
      version = "1.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/pangocairo-1.0/-/pangocairo-1.0-1.0.0-4.0.0-beta.19.tgz";
        sha512 = "LSyxXfJ3/FgOHW4pZt2w1mPyi4Gi1LduikLH5X5XtTaPDqA3czf9G72V3QJ/P8RI+LZ/9KWhhg1ZuGF/uhQyZA==";
      };
    };
    "@girs/polkit-1.0-1.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_polkit-1.0";
      packageName = "@girs/polkit-1.0";
      version = "1.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/polkit-1.0/-/polkit-1.0-1.0.0-4.0.0-beta.19.tgz";
        sha512 = "1AaBJDsEYvbS4iuqqbZ/k9nTOPDn7gYM870SH77wNrVNOw4CT5FTidfHj45jYBviiRGLGod0MPQ/1DOCIv/rSQ==";
      };
    };
    "@girs/polkitagent-1.0-1.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_polkitagent-1.0";
      packageName = "@girs/polkitagent-1.0";
      version = "1.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/polkitagent-1.0/-/polkitagent-1.0-1.0.0-4.0.0-beta.19.tgz";
        sha512 = "qLZVTunA2VczYgqhqobOT5NSelDfvuPV6JIXoo7Y5JJpM37zw58PiWLmvMLSiPiUXAOXQuCJM7pcHNlyEdvYLQ==";
      };
    };
    "@girs/shell-15-15.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_shell-15";
      packageName = "@girs/shell-15";
      version = "15.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/shell-15/-/shell-15-15.0.0-4.0.0-beta.19.tgz";
        sha512 = "2IzUX8hbcS2byQtyqmgtblDP/McpYOnfXCf5mWliJErHyaYvF7Ki+skProaJKnEuRC8t9C/c+kkJKVFSRXes7w==";
      };
    };
    "@girs/shew-0-0.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_shew-0";
      packageName = "@girs/shew-0";
      version = "0.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/shew-0/-/shew-0-0.0.0-4.0.0-beta.19.tgz";
        sha512 = "Fc50IgkiAIrixb8iGBV2crbi0wVL/fKV8cg/KnS7XfFmczLfw7NGnlp+Cbcm0GS5totgR91RrT+RQjEShX7oJQ==";
      };
    };
    "@girs/st-15-15.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_st-15";
      packageName = "@girs/st-15";
      version = "15.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/st-15/-/st-15-15.0.0-4.0.0-beta.19.tgz";
        sha512 = "+4xg3T672KUYgIf9hAkZsD5ALKvWveRq410xJ8qkHEj7adRG+MFBjt+xXr7RPmvTRw74pvESAXA0M+JY4x3kXw==";
      };
    };
    "@girs/upowerglib-1.0-0.99.1-4.0.0-beta.19" = {
      name = "_at_girs_slash_upowerglib-1.0";
      packageName = "@girs/upowerglib-1.0";
      version = "0.99.1-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/upowerglib-1.0/-/upowerglib-1.0-0.99.1-4.0.0-beta.19.tgz";
        sha512 = "8Do2336E1fkaWPLvrHQeIAs9cvITD3d7jLCKhPEx1NtthYjCQYP6FwzWIzNmCbJ62xskvuxBsfsts5C2jleqBw==";
      };
    };
    "@girs/xfixes-4.0-4.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_xfixes-4.0";
      packageName = "@girs/xfixes-4.0";
      version = "4.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/xfixes-4.0/-/xfixes-4.0-4.0.0-4.0.0-beta.19.tgz";
        sha512 = "WJES/KPgiAc6f5skUCYlIlijSF6eSibH06KUKP+xHgvdYd3DDmeu+L6I+I557rndcvFDFyD8I7CiJs9knUdPEg==";
      };
    };
    "@girs/xlib-2.0-2.0.0-4.0.0-beta.19" = {
      name = "_at_girs_slash_xlib-2.0";
      packageName = "@girs/xlib-2.0";
      version = "2.0.0-4.0.0-beta.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@girs/xlib-2.0/-/xlib-2.0-2.0.0-4.0.0-beta.19.tgz";
        sha512 = "+xAeOIyMuXdRUdfUe5yOqpgfWN/zcYD6WE+zNmlvosXneGz6D13N/s58qqJ+uDXqNP9n/z2w2iROMxXsZtJlUw==";
      };
    };
    "@humanfs/core-0.19.1" = {
      name = "_at_humanfs_slash_core";
      packageName = "@humanfs/core";
      version = "0.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanfs/core/-/core-0.19.1.tgz";
        sha512 = "5DyQ4+1JEUzejeK1JGICcideyfUbGixgS9jNgex5nqkW+cY7WZhxBigmieN5Qnw9ZosSNVC9KQKyb+GUaGyKUA==";
      };
    };
    "@humanfs/node-0.16.6" = {
      name = "_at_humanfs_slash_node";
      packageName = "@humanfs/node";
      version = "0.16.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanfs/node/-/node-0.16.6.tgz";
        sha512 = "YuI2ZHQL78Q5HbhDiBA1X4LmYdXCKCMQIfw0pw7piHJwyREFebJUvrQN4cMssyES6x+vfUbx1CIpaQUKYdQZOw==";
      };
    };
    "@humanwhocodes/module-importer-1.0.1" = {
      name = "_at_humanwhocodes_slash_module-importer";
      packageName = "@humanwhocodes/module-importer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/module-importer/-/module-importer-1.0.1.tgz";
        sha512 = "bxveV4V8v5Yb4ncFTT3rPSgZBOpCkjfK0y4oVVVJwIuDVBRMDXrPyXRL988i5ap9m9bnyEEjWfm5WkBmtffLfA==";
      };
    };
    "@humanwhocodes/retry-0.3.1" = {
      name = "_at_humanwhocodes_slash_retry";
      packageName = "@humanwhocodes/retry";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/retry/-/retry-0.3.1.tgz";
        sha512 = "JBxkERygn7Bv/GbN5Rv8Ul6LVknS+5Bp6RgDC/O8gEBU/yeH5Ui5C/OlWrTb6qct7LjjfT6Re2NxB0ln0yYybA==";
      };
    };
    "@humanwhocodes/retry-0.4.1" = {
      name = "_at_humanwhocodes_slash_retry";
      packageName = "@humanwhocodes/retry";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/retry/-/retry-0.4.1.tgz";
        sha512 = "c7hNEllBlenFTHBky65mhq8WD2kbN9Q6gk0bTk8lSBvc554jpXSkST1iePudpt7+A/AQvuHs9EMqjHDXMY1lrA==";
      };
    };
    "@pkgr/core-0.1.1" = {
      name = "_at_pkgr_slash_core";
      packageName = "@pkgr/core";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pkgr/core/-/core-0.1.1.tgz";
        sha512 = "cq8o4cWH0ibXh9VGi5P20Tu9XF/0fFXl9EUinr9QfTM7a7p0oTA4iJRCQWppXR1Pg8dSM0UCItCkPwsk9qWWYA==";
      };
    };
    "@types/estree-1.0.6" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.6.tgz";
        sha512 = "AYnb1nQyY49te+VRAVgmzfcgjYS91mY5P0TKUDCLEM+gNnA+3T6rWITXRLYCpahpqSQbN5cE+gHpnPyXjHWxcw==";
      };
    };
    "@types/json-schema-7.0.15" = {
      name = "_at_types_slash_json-schema";
      packageName = "@types/json-schema";
      version = "7.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/json-schema/-/json-schema-7.0.15.tgz";
        sha512 = "5+fP8P8MFNC+AyZCDxrB2pkZFPGzqQWUzpSeuuVLvm8VMcorNYavBqoFcxK8bQz4Qsbn4oUEEem4wDLfcysGHA==";
      };
    };
    "acorn-8.14.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.14.0.tgz";
        sha512 = "cl669nCJTZBsL97OF4kUQm5g5hC2uihk0NxY3WENAC0TYdILVkAyHymAntgxGkl7K+t0cXIrH5siy5S4XkFycA==";
      };
    };
    "acorn-jsx-5.3.2" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-5.3.2.tgz";
        sha512 = "rq9s+JNhf0IChjtDXxllJ7g41oZk5SlXtp0LHwyA5cejwn7vKmKp4pPri6YEePv2PU65sAsegbXtIinmDFDXgQ==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "are-docs-informative-0.0.2" = {
      name = "are-docs-informative";
      packageName = "are-docs-informative";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-docs-informative/-/are-docs-informative-0.0.2.tgz";
        sha512 = "ixiS0nLNNG5jNQzgZJNoUpBKdo9yTYZMGJ+QgT2jmjR7G7+QHRCc4v6LQ3NgE7EBJq+o0ams3waJwkrlBom8Ig==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "callsites-3.1.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
        sha512 = "P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "comment-parser-1.4.1" = {
      name = "comment-parser";
      packageName = "comment-parser";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/comment-parser/-/comment-parser-1.4.1.tgz";
        sha512 = "buhp5kePrmda3vhc5B9t7pUQXAb2Tnd0qgpkIhPhkHXxJpiPJ11H0ZEU0oBpJ2QztSbzG/ZxMj/CHsYJqRHmyg==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "cross-spawn-7.0.6" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
        sha512 = "uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
      };
    };
    "debug-4.3.7" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.7.tgz";
        sha512 = "Er2nc/H7RrMXZBFCEim6TCmMk02Z8vLC2Rbi1KEBggpo0fS6l0S1nnapwmIi3yW/+GOJap1Krg4w0Hg80oCqgQ==";
      };
    };
    "deep-is-0.1.4" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.4.tgz";
        sha512 = "oIPzksmTg4/MriiaYGO+okXDT7ztn/w3Eptv/+gSIdMdKsJo0u4CfYNFJPy+4SKMuCqGw2wxnA+URMg3t8a/bQ==";
      };
    };
    "es-module-lexer-1.5.4" = {
      name = "es-module-lexer";
      packageName = "es-module-lexer";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-module-lexer/-/es-module-lexer-1.5.4.tgz";
        sha512 = "MVNK56NiMrOwitFB7cqDwq0CQutbw+0BvLshJSse0MUNU+y1FC3bUS/AQg7oUng+/wKrrki7JfmwtVHkVfPLlw==";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "eslint-9.16.0" = {
      name = "eslint";
      packageName = "eslint";
      version = "9.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint/-/eslint-9.16.0.tgz";
        sha512 = "whp8mSQI4C8VXd+fLgSM0lh3UlmcFtVwUQjyKCFfsp+2ItAIYhlq/hqGahGqHE6cv9unM41VlqKk2VtKYR2TaA==";
      };
    };
    "eslint-plugin-jsdoc-50.6.0" = {
      name = "eslint-plugin-jsdoc";
      packageName = "eslint-plugin-jsdoc";
      version = "50.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-plugin-jsdoc/-/eslint-plugin-jsdoc-50.6.0.tgz";
        sha512 = "tCNp4fR79Le3dYTPB0dKEv7yFyvGkUCa+Z3yuTrrNGGOxBlXo9Pn0PEgroOZikUQOGjxoGMVKNjrOHcYEdfszg==";
      };
    };
    "eslint-scope-8.2.0" = {
      name = "eslint-scope";
      packageName = "eslint-scope";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-scope/-/eslint-scope-8.2.0.tgz";
        sha512 = "PHlWUfG6lvPc3yvP5A4PNyBL1W8fkDUccmI21JUu/+GKZBoH/W5u6usENXUrWFRsyoW5ACUjFGgAFQp5gUlb/A==";
      };
    };
    "eslint-visitor-keys-3.4.3" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "3.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-3.4.3.tgz";
        sha512 = "wpc+LXeiyiisxPlEkUzU6svyS1frIO3Mgxj1fdy7Pm8Ygzguax2N3Fa/D/ag1WqbOprdI+uY6wMUl8/a2G+iag==";
      };
    };
    "eslint-visitor-keys-4.2.0" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-4.2.0.tgz";
        sha512 = "UyLnSehNt62FFhSwjZlHmeokpRK59rcz29j+F1/aDgbkbRTk7wIc9XzdoasMUbRNKDM0qQt/+BJ4BrpFeABemw==";
      };
    };
    "espree-10.3.0" = {
      name = "espree";
      packageName = "espree";
      version = "10.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-10.3.0.tgz";
        sha512 = "0QYC8b24HWY8zjRnDTL6RiHfDbAWn63qb4LMj1Z4b076A4une81+z03Kg7l7mn/48PUTqoLptSXez8oknU8Clg==";
      };
    };
    "esquery-1.6.0" = {
      name = "esquery";
      packageName = "esquery";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esquery/-/esquery-1.6.0.tgz";
        sha512 = "ca9pw9fomFcKPvFLXhBKUK90ZvGibiGOvRJNbjljY7s7uq/5YO4BOzcYtJqExdx99rF6aAcnRxHmcUHcz6sQsg==";
      };
    };
    "esrecurse-4.3.0" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.3.0.tgz";
        sha512 = "KmfKL3b6G+RXvP8N1vr3Tq1kL/oCFgn2NYXEtqP8/L3pKapUA4G8cFVaoF3SU323CD4XypR/ffioHmkti6/Tag==";
      };
    };
    "estraverse-5.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.3.0.tgz";
        sha512 = "MMdARuVEQziNTeJD8DgMqmhwR11BRQ/cBP+pLtYdSTnf3MIO8fFeiINEbX36ZdNlfU/7A9f3gUw49B3oQsvwBA==";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha512 = "DCXu6Ifhqcks7TZKY3Hxp3y6qphY5SJZmrWMDrKcERSOXWQdMhU9Ig/PYrzyw/ul9jOIyh0N4M0tbC5hodg8dw==";
      };
    };
    "file-entry-cache-8.0.0" = {
      name = "file-entry-cache";
      packageName = "file-entry-cache";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-entry-cache/-/file-entry-cache-8.0.0.tgz";
        sha512 = "XXTUwCvisa5oacNGRP9SfNtYBNAMi+RPwBFmblZEF7N7swHYQS6/Zfk7SRwx4D5j3CH211YNRco1DEMNVfZCnQ==";
      };
    };
    "find-up-5.0.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-5.0.0.tgz";
        sha512 = "78/PXT1wlLLDgTzDs7sjq9hzz0vXD+zn+7wypEe4fXQxCmdmqfGsEPQxmiCSQI3ajFV91bVSsvNtrJRiW6nGng==";
      };
    };
    "flat-cache-4.0.1" = {
      name = "flat-cache";
      packageName = "flat-cache";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/flat-cache/-/flat-cache-4.0.1.tgz";
        sha512 = "f7ccFPK3SXFHpx15UIGyRJ/FJQctuKZ0zVuN3frBo4HnK3cay9VEW0R6yPYFHC0AgqhukPzKjq22t5DmAyqGyw==";
      };
    };
    "flatted-3.3.1" = {
      name = "flatted";
      packageName = "flatted";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/flatted/-/flatted-3.3.1.tgz";
        sha512 = "X8cqMLLie7KsNUDSdzeN8FYK9rEt4Dt67OsG/DNGnYTSDBG4uFAJFBnUeiV+zCVAvwFy56IjM9sH51jVaEhNxw==";
      };
    };
    "glob-parent-6.0.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-6.0.2.tgz";
        sha512 = "XxwI8EOhVQgWp6iDL+3b0r86f4d6AX6zSU55HfB4ydCEuXLXc5FcYeOu+nnGftS4TEju/11rt4KJPTMgbfmv4A==";
      };
    };
    "globals-14.0.0" = {
      name = "globals";
      packageName = "globals";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-14.0.0.tgz";
        sha512 = "oahGvuMGQlPw/ivIYBjVSrWAfWLBeku5tpPE2fOPLi+WHffIWbuh2tCjhyQhTBPMf5E9jDEH4FOmTYgYwbKwtQ==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "ignore-5.3.2" = {
      name = "ignore";
      packageName = "ignore";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-5.3.2.tgz";
        sha512 = "hsBTNUqQTDwkWtcdYI2i06Y/nUBEsNEDJKjWdigLvegy8kDuJAS8uRlpkkcQpyEXL0Z/pjDy5HBmMjRCJ2gq+g==";
      };
    };
    "import-fresh-3.3.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.3.0.tgz";
        sha512 = "veYYhQa+D1QBKznvhUHxb8faxlrwUnxseDAbAp457E0wLNio2bOSKnjYDhMj+YiAq61xrMGhQk9iXVk5FzgQMw==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha512 = "JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "js-yaml-4.1.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.0.tgz";
        sha512 = "wpxZs9NoxZaJESJGIZTyDEaYpl0FKSA+FB9aJiyemKhMwkxQg63h4T1KJgUGHpTqPDNRcmmYLugrRjJlBtWvRA==";
      };
    };
    "jsdoc-type-pratt-parser-4.1.0" = {
      name = "jsdoc-type-pratt-parser";
      packageName = "jsdoc-type-pratt-parser";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsdoc-type-pratt-parser/-/jsdoc-type-pratt-parser-4.1.0.tgz";
        sha512 = "Hicd6JK5Njt2QB6XYFS7ok9e37O8AYk3jTcppG4YVQnYjOemymvTcmc7OWsmq/Qqj5TdRFO5/x/tIPmBeRtGHg==";
      };
    };
    "json-buffer-3.0.1" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.1.tgz";
        sha512 = "4bV5BfR2mqfQTJm+V5tPPdf+ZpuhiIvTuAB5g8kcrXOZpTT/QwwVRWBywX1ozr6lEuPdbHxwaJlm9G6mI2sfSQ==";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-stable-stringify-without-jsonify-1.0.1" = {
      name = "json-stable-stringify-without-jsonify";
      packageName = "json-stable-stringify-without-jsonify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz";
        sha512 = "Bdboy+l7tA3OGW6FjyFHWkP5LuByj1Tk33Ljyq0axyzdk9//JSi2u3fP1QSmd1KNwq6VOKYGlAu87CisVir6Pw==";
      };
    };
    "keyv-4.5.4" = {
      name = "keyv";
      packageName = "keyv";
      version = "4.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-4.5.4.tgz";
        sha512 = "oxVHkHR/EJf2CNXnWxRLW6mg7JyCCUcG0DtEGmL2ctUo1PNTin1PUil+r/+4r5MpVgC/fn1kjsx7mjSujKqIpw==";
      };
    };
    "levn-0.4.1" = {
      name = "levn";
      packageName = "levn";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.4.1.tgz";
        sha512 = "+bT2uH4E5LGE7h/n3evcS/sQlJXCpIp6ym8OWJ5eV6+67Dsql/LaaT7qJBAt2rzfoa/5QBGBhxDix1dMt2kQKQ==";
      };
    };
    "locate-path-6.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-6.0.0.tgz";
        sha512 = "iPZK6eYjbxRu3uB4/WZ3EsEIMJFMqAoopl3R+zuq0UjcAm/MO6KCweDgPfP3elTztoKP3KtnVHxTn2NHBSDVUw==";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "natural-compare-1.4.0" = {
      name = "natural-compare";
      packageName = "natural-compare";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/natural-compare/-/natural-compare-1.4.0.tgz";
        sha512 = "OWND8ei3VtNC9h7V60qff3SVobHr996CTwgxubgyQYEpg290h9J0buyECNNJexkFm5sOajh5G116RYA1c8ZMSw==";
      };
    };
    "optionator-0.9.4" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.9.4.tgz";
        sha512 = "6IpQ7mKUxRcZNLIObR0hz7lxsapSSIYNZJwXPGeF0mTVqGKFIXj1DQcMoT22S3ROcLyY/rz0PWaWZ9ayWmad9g==";
      };
    };
    "p-limit-3.1.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-3.1.0.tgz";
        sha512 = "TYOanM3wGwNGsZN2cVTYPArw454xnXj5qmWF1bEoAc4+cU/ol7GVh7odevjp1FNHduHc3KZMcFduxU5Xc6uJRQ==";
      };
    };
    "p-locate-5.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-5.0.0.tgz";
        sha512 = "LaNjtRWUBY++zB5nE/NwcaoMylSPk+S+ZHNB1TzdbMJMny6dynpAGt7X/tl/QYq3TIeE6nxHppbo2LGymrG5Pw==";
      };
    };
    "parent-module-1.0.1" = {
      name = "parent-module";
      packageName = "parent-module";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
        sha512 = "GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
      };
    };
    "parse-imports-2.1.1" = {
      name = "parse-imports";
      packageName = "parse-imports";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-imports/-/parse-imports-2.1.1.tgz";
        sha512 = "TDT4HqzUiTMO1wJRwg/t/hYk8Wdp3iF/ToMIlAoVQfL1Xs/sTxq1dKWSMjMbQmIarfWKymOyly40+zmPHXMqCA==";
      };
    };
    "path-exists-4.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
        sha512 = "ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "prelude-ls-1.2.1" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.2.1.tgz";
        sha512 = "vkcDPrRZo1QZLbn5RLGPpg/WmIQ65qoWWhcGKf/b5eplkkarX0m9z8ppCat4mlOqUsWpyNuYgO3VRyrYHSzX5g==";
      };
    };
    "punycode-2.3.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.3.1.tgz";
        sha512 = "vYt7UD1U9Wg6138shLtLOvdAu+8DsC/ilFtEVHcH+wydcSpNE20AfSOduf6MkRFahL5FY7X1oU7nKVZFtfq8Fg==";
      };
    };
    "resolve-from-4.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
        sha512 = "pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
      };
    };
    "semver-7.6.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.6.3.tgz";
        sha512 = "oVekP1cKtI+CTDvHWYFUcMtsK/00wmAEfyqKfNdARm8u1wNVhSgaX7A8d4UuIlUI5e84iEwOhs7ZPYRmzU9U6A==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "slashes-3.0.12" = {
      name = "slashes";
      packageName = "slashes";
      version = "3.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/slashes/-/slashes-3.0.12.tgz";
        sha512 = "Q9VME8WyGkc7pJf6QEkj3wE+2CnvZMI+XJhwdTPR8Z/kWQRXi7boAWLDibRPyHRTUTPx5FaU7MsyrjI3yLB4HA==";
      };
    };
    "spdx-exceptions-2.5.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.5.0.tgz";
        sha512 = "PiU42r+xO4UbUS1buo3LPJkjlO7430Xn5SVAhdpzzsPHsjbYVflnnFdATgabnLude+Cqu25p6N+g2lw/PFsa4w==";
      };
    };
    "spdx-expression-parse-4.0.0" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-4.0.0.tgz";
        sha512 = "Clya5JIij/7C6bRR22+tnGXbc4VKlibKSVj2iHvVeX5iMW7s1SIQlqu699JkODJJIhh/pUu8L0/VLh8xflD+LQ==";
      };
    };
    "spdx-license-ids-3.0.18" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.18.tgz";
        sha512 = "xxRs31BqRYHwiMzudOrpSiHtZ8i/GeionCBDSilhYRj+9gIcI8wCZTlXZKu9vZIVqViP3dcp9qE5G6AlIaD+TQ==";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "synckit-0.9.1" = {
      name = "synckit";
      packageName = "synckit";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/synckit/-/synckit-0.9.1.tgz";
        sha512 = "7gr8p9TQP6RAHusBOSLs46F4564ZrjV8xFmw5zCmgmhGUcw2hxsShhJ6CEiHQMgPDwAQ1fWHPM0ypc4RMAig4A==";
      };
    };
    "tslib-2.6.3" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.6.3.tgz";
        sha512 = "xNvxJEOUiWPGhUuUdQgAJPKOOJfGnIyKySOc09XkKsgdUV/3E2zvwZYdejjmRgPCgcym1juLH3226yA7sEFJKQ==";
      };
    };
    "type-check-0.4.0" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.4.0.tgz";
        sha512 = "XleUoc9uwGXqjWwXaUTZAmzMcFZ5858QA2vvx1Ur5xIcixXIP+8LnFDgRplU30us6teqdlskFfu+ae4K79Ooew==";
      };
    };
    "typescript-5.7.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.7.2.tgz";
        sha512 = "i5t66RHxDvVN40HfDd1PsEThGNnlMCMT3jMUuoh9/0TaqWevNontacunWyN02LA9/fIbEWlcHZcgTKb9QoaLfg==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "word-wrap-1.2.5" = {
      name = "word-wrap";
      packageName = "word-wrap";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.5.tgz";
        sha512 = "BN22B5eaMMI9UMtjrGd5g5eCYPpCPDUy0FJXbYsaT5zYxjFOckS53SQDE3pWkVoWpHXVb3BrYcEN4Twa55B5cA==";
      };
    };
    "yocto-queue-0.1.0" = {
      name = "yocto-queue";
      packageName = "yocto-queue";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz";
        sha512 = "rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==";
      };
    };
  };
  args = {
    name = "gnome-rectangle";
    packageName = "gnome-rectangle";
    version = "1.0.0";
    src = ./..;
    dependencies = [
      sources."@es-joy/jsdoccomment-0.49.0"
      (sources."@eslint-community/eslint-utils-4.4.0" // {
        dependencies = [
          sources."eslint-visitor-keys-3.4.3"
        ];
      })
      sources."@eslint-community/regexpp-4.12.1"
      sources."@eslint/config-array-0.19.0"
      sources."@eslint/core-0.9.0"
      sources."@eslint/eslintrc-3.2.0"
      sources."@eslint/js-9.16.0"
      sources."@eslint/object-schema-2.1.4"
      sources."@eslint/plugin-kit-0.2.3"
      sources."@girs/accountsservice-1.0-1.0.0-4.0.0-beta.17"
      sources."@girs/adw-1-1.7.0-4.0.0-beta.19"
      sources."@girs/atk-1.0-2.54.0-4.0.0-beta.19"
      sources."@girs/cairo-1.0-1.0.0-4.0.0-beta.19"
      sources."@girs/cally-15-15.0.0-4.0.0-beta.19"
      sources."@girs/clutter-15-15.0.0-4.0.0-beta.19"
      sources."@girs/cogl-15-15.0.0-4.0.0-beta.19"
      sources."@girs/cogl-2.0-2.0.0-4.0.0-beta.19"
      sources."@girs/coglpango-15-15.0.0-4.0.0-beta.19"
      sources."@girs/freetype2-2.0-2.0.0-4.0.0-beta.19"
      sources."@girs/gck-2-4.3.0-4.0.0-beta.19"
      sources."@girs/gcr-4-4.3.0-4.0.0-beta.19"
      sources."@girs/gdesktopenums-3.0-3.0.0-4.0.0-beta.19"
      sources."@girs/gdk-4.0-4.0.0-4.0.0-beta.19"
      sources."@girs/gdkpixbuf-2.0-2.0.0-4.0.0-beta.19"
      sources."@girs/gdm-1.0-1.0.0-4.0.0-beta.19"
      sources."@girs/gio-2.0-2.82.2-4.0.0-beta.19"
      sources."@girs/gjs-4.0.0-beta.19"
      sources."@girs/gl-1.0-1.0.0-4.0.0-beta.19"
      sources."@girs/glib-2.0-2.82.2-4.0.0-beta.19"
      sources."@girs/gmodule-2.0-2.0.0-4.0.0-beta.19"
      sources."@girs/gnome-shell-47.0.0"
      sources."@girs/gnomebg-4.0-4.0.0-4.0.0-beta.19"
      sources."@girs/gnomebluetooth-3.0-3.0.0-4.0.0-beta.19"
      sources."@girs/gnomedesktop-4.0-4.0.0-4.0.0-beta.19"
      sources."@girs/gobject-2.0-2.82.2-4.0.0-beta.19"
      sources."@girs/graphene-1.0-1.0.0-4.0.0-beta.19"
      sources."@girs/gsk-4.0-4.0.0-4.0.0-beta.19"
      sources."@girs/gtk-4.0-4.16.3-4.0.0-beta.19"
      sources."@girs/gvc-1.0-1.0.0-4.0.0-beta.19"
      sources."@girs/harfbuzz-0.0-9.0.0-4.0.0-beta.19"
      sources."@girs/meta-15-15.0.0-4.0.0-beta.19"
      sources."@girs/mtk-15-15.0.0-4.0.0-beta.19"
      sources."@girs/nm-1.0-1.49.4-4.0.0-beta.19"
      sources."@girs/pango-1.0-1.54.0-4.0.0-beta.19"
      sources."@girs/pangocairo-1.0-1.0.0-4.0.0-beta.19"
      sources."@girs/polkit-1.0-1.0.0-4.0.0-beta.19"
      sources."@girs/polkitagent-1.0-1.0.0-4.0.0-beta.19"
      sources."@girs/shell-15-15.0.0-4.0.0-beta.19"
      sources."@girs/shew-0-0.0.0-4.0.0-beta.19"
      sources."@girs/st-15-15.0.0-4.0.0-beta.19"
      sources."@girs/upowerglib-1.0-0.99.1-4.0.0-beta.19"
      sources."@girs/xfixes-4.0-4.0.0-4.0.0-beta.19"
      sources."@girs/xlib-2.0-2.0.0-4.0.0-beta.19"
      sources."@humanfs/core-0.19.1"
      (sources."@humanfs/node-0.16.6" // {
        dependencies = [
          sources."@humanwhocodes/retry-0.3.1"
        ];
      })
      sources."@humanwhocodes/module-importer-1.0.1"
      sources."@humanwhocodes/retry-0.4.1"
      sources."@pkgr/core-0.1.1"
      sources."@types/estree-1.0.6"
      sources."@types/json-schema-7.0.15"
      sources."acorn-8.14.0"
      sources."acorn-jsx-5.3.2"
      sources."ajv-6.12.6"
      sources."ansi-styles-4.3.0"
      sources."are-docs-informative-0.0.2"
      sources."argparse-2.0.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."callsites-3.1.0"
      sources."chalk-4.1.2"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."comment-parser-1.4.1"
      sources."concat-map-0.0.1"
      sources."cross-spawn-7.0.6"
      sources."debug-4.3.7"
      sources."deep-is-0.1.4"
      sources."es-module-lexer-1.5.4"
      sources."escape-string-regexp-4.0.0"
      sources."eslint-9.16.0"
      sources."eslint-plugin-jsdoc-50.6.0"
      sources."eslint-scope-8.2.0"
      sources."eslint-visitor-keys-4.2.0"
      sources."espree-10.3.0"
      sources."esquery-1.6.0"
      sources."esrecurse-4.3.0"
      sources."estraverse-5.3.0"
      sources."esutils-2.0.3"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fast-levenshtein-2.0.6"
      sources."file-entry-cache-8.0.0"
      sources."find-up-5.0.0"
      sources."flat-cache-4.0.1"
      sources."flatted-3.3.1"
      sources."glob-parent-6.0.2"
      sources."globals-14.0.0"
      sources."has-flag-4.0.0"
      sources."ignore-5.3.2"
      sources."import-fresh-3.3.0"
      sources."imurmurhash-0.1.4"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."isexe-2.0.0"
      sources."js-yaml-4.1.0"
      sources."jsdoc-type-pratt-parser-4.1.0"
      sources."json-buffer-3.0.1"
      sources."json-schema-traverse-0.4.1"
      sources."json-stable-stringify-without-jsonify-1.0.1"
      sources."keyv-4.5.4"
      sources."levn-0.4.1"
      sources."locate-path-6.0.0"
      sources."lodash.merge-4.6.2"
      sources."minimatch-3.1.2"
      sources."ms-2.1.3"
      sources."natural-compare-1.4.0"
      sources."optionator-0.9.4"
      sources."p-limit-3.1.0"
      sources."p-locate-5.0.0"
      sources."parent-module-1.0.1"
      sources."parse-imports-2.1.1"
      sources."path-exists-4.0.0"
      sources."path-key-3.1.1"
      sources."prelude-ls-1.2.1"
      sources."punycode-2.3.1"
      sources."resolve-from-4.0.0"
      sources."semver-7.6.3"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."slashes-3.0.12"
      sources."spdx-exceptions-2.5.0"
      sources."spdx-expression-parse-4.0.0"
      sources."spdx-license-ids-3.0.18"
      sources."strip-json-comments-3.1.1"
      sources."supports-color-7.2.0"
      sources."synckit-0.9.1"
      sources."tslib-2.6.3"
      sources."type-check-0.4.0"
      sources."typescript-5.7.2"
      sources."uri-js-4.4.1"
      sources."which-2.0.2"
      sources."word-wrap-1.2.5"
      sources."yocto-queue-0.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Magnet/Rectangle like manual tiling";
      homepage = "https://github.com/acristoffers/gnome-rectangle#readme";
      license = "LGPL-3.0-or-later";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
